probod:
  api:
    cors:
      allowed-origins: ["http://localhost:5173"]
  aws:
    access-key-id: "probod"
    secret-access-key: "thisisnotasecret"
    endpoint: "http://127.0.0.1:9000"
  openai:
    api-key: "thisisnotasecret"
    temperature: 0.1
    model-name: "gpt-4o"
