# Copyright (c) 2026 Probo Inc <hello@probo.com>.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

extend type Query {
    slackIdentityBindPreview(token: String!): SlackIdentityBindPreview!
        @goField(forceResolver: true)
}

extend type Mutation {
    confirmSlackIdentityBinding(
        input: ConfirmSlackIdentityBindingInput!
    ): ConfirmSlackIdentityBindingPayload!
    deleteSlackIdentityBinding(
        input: DeleteSlackIdentityBindingInput!
    ): DeleteSlackIdentityBindingPayload!
}

type SlackIdentityBinding implements Node {
    id: ID!
    teamId: String!
    slackUserId: String!
    createdAt: Datetime!
    updatedAt: Datetime!
}

type SlackIdentityBindPreview {
    teamId: String!
    slackUserId: String!
}

input ConfirmSlackIdentityBindingInput {
    token: String!
}

type ConfirmSlackIdentityBindingPayload {
    slackIdentityBinding: SlackIdentityBinding!
}

input DeleteSlackIdentityBindingInput {
    id: ID!
}

type DeleteSlackIdentityBindingPayload {
    slackIdentityBindingId: ID!
}
