ALTER TYPE document_type RENAME VALUE 'ISMS' TO 'GOVERNANCE';
ALTER TYPE document_type ADD VALUE 'PLAN';
ALTER TYPE document_type ADD VALUE 'REGISTER';
ALTER TYPE document_type ADD VALUE 'RECORD';
ALTER TYPE document_type ADD VALUE 'REPORT';
ALTER TYPE document_type ADD VALUE 'TEMPLATE';
