-- Rename NONCONFORMITY to MINOR_NONCONFORMITY and add MAJOR_NONCONFORMITY
ALTER TYPE findings_kind RENAME VALUE 'NONCONFORMITY' TO 'MINOR_NONCONFORMITY';
ALTER TYPE findings_kind ADD VALUE 'MAJOR_NONCONFORMITY';
