// Copyright (c) 2026 Probo Inc <hello@probo.com>.
//
// Permission to use, copy, modify, and/or distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
// REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
// AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
// INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
// LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
// OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.

// Code generated by internal/cmd/genactions; DO NOT EDIT.

package iam

// DeclaredActions returns every IAM action constant declared in this package.
func DeclaredActions() []string {
	return []string{
		ActionAuditLogEntryGet,
		ActionAuditLogEntryList,
		ActionConnectorGet,
		ActionIdentityDelete,
		ActionIdentityGet,
		ActionIdentityUpdate,
		ActionInvitationAccept,
		ActionInvitationCreate,
		ActionInvitationDelete,
		ActionInvitationGet,
		ActionInvitationList,
		ActionMembershipProfileActivate,
		ActionMembershipProfileCreate,
		ActionMembershipProfileDeactivate,
		ActionMembershipProfileDelete,
		ActionMembershipProfileGet,
		ActionMembershipProfileList,
		ActionMembershipProfileUpdate,
		ActionMembershipRoleSetOwner,
		ActionMembershipDelete,
		ActionMembershipGet,
		ActionMembershipList,
		ActionMembershipUpdate,
		ActionOAuth2ConsentApprove,
		ActionOAuth2ConsentGet,
		ActionOrganizationCreate,
		ActionOrganizationDelete,
		ActionOrganizationGet,
		ActionOrganizationList,
		ActionOrganizationUpdate,
		ActionPersonalAPIKeyCreate,
		ActionPersonalAPIKeyDelete,
		ActionPersonalAPIKeyGet,
		ActionPersonalAPIKeyList,
		ActionPersonalAPIKeyUpdate,
		ActionSAMLConfigurationCreate,
		ActionSAMLConfigurationDelete,
		ActionSAMLConfigurationGet,
		ActionSAMLConfigurationList,
		ActionSAMLConfigurationUpdate,
		ActionSCIMBridgeCreate,
		ActionSCIMBridgeDelete,
		ActionSCIMBridgeGet,
		ActionSCIMBridgeUpdate,
		ActionSCIMConfigurationCreate,
		ActionSCIMConfigurationDelete,
		ActionSCIMConfigurationGet,
		ActionSCIMConfigurationUpdate,
		ActionSCIMEventGet,
		ActionSCIMEventList,
		ActionSessionGet,
		ActionSessionList,
		ActionSessionRevoke,
		ActionSessionRevokeAll,
	}
}
