// Code generated by mcpgen. DO NOT EDIT.

package types

import (
	"go.probo.inc/mcpgen/mcp"
	"go.probo.inc/probo/pkg/coredata"
	"go.probo.inc/probo/pkg/gid"
	"go.probo.inc/probo/pkg/page"
	"time"
)

// Tool input schemas
var (
	AddVendorToolInputSchema          = mcp.MustUnmarshalSchema(`{"type":"object","required":["organization_id","name"],"properties":{"created_at":{"type":"string","description":"Creation timestamp","format":"date-time"},"description":{"type":"string","description":"Vendor description"},"name":{"type":"string","description":"Vendor name"},"organization_id":{"type":"string","format":"string"},"updated_at":{"type":"string","description":"Update timestamp","format":"date-time"}}}`)
	AddVendorToolOutputSchema         = mcp.MustUnmarshalSchema(`{"type":"object","required":["vendor"],"properties":{"vendor":{"type":"object","required":["id","name","organization_id","created_at","updated_at"],"properties":{"created_at":{"type":"string","description":"Creation timestamp","format":"date-time"},"description":{"description":"Vendor description"},"id":{"type":"string","format":"string"},"name":{"type":"string","description":"Vendor name"},"organization_id":{"type":"string","format":"string"},"updated_at":{"type":"string","description":"Update timestamp","format":"date-time"}}}}}`)
	ListOrganizationsToolInputSchema  = mcp.MustUnmarshalSchema(`{"type":"object","properties":{"organization_id":{"type":"string","format":"string"}}}`)
	ListOrganizationsToolOutputSchema = mcp.MustUnmarshalSchema(`{"type":"object","properties":{"organizations":{"type":"array","items":{"type":"object","required":["id","name","description","created_at","updated_at"],"properties":{"created_at":{"type":"string","description":"Creation timestamp","format":"date-time"},"description":{"description":"Organization description"},"id":{"type":"string","format":"string"},"name":{"type":"string","description":"Organization name"},"updated_at":{"type":"string","description":"Update timestamp","format":"date-time"}}}}}}`)
	ListVendorsToolInputSchema        = mcp.MustUnmarshalSchema(`{"type":"object","required":["organization_id"],"properties":{"cursor":{"type":"string","format":"string"},"filter":{"type":"object","properties":{"snapshot_id":{"type":"string","format":"string"}}},"order_by":{"type":"object","required":["field","direction"],"properties":{"direction":{"type":"string","enum":["asc","desc"]},"field":{"type":"string","enum":["created_at","updated_at","name"]}}},"organization_id":{"type":"string","format":"string"},"size":{"type":"integer","description":"Page size"}}}`)
	ListVendorsToolOutputSchema       = mcp.MustUnmarshalSchema(`{"type":"object","required":["vendors"],"properties":{"next_cursor":{"type":"string","format":"string"},"vendors":{"type":"array","items":{"type":"object","required":["id","name","organization_id","created_at","updated_at"],"properties":{"created_at":{"type":"string","description":"Creation timestamp","format":"date-time"},"description":{"description":"Vendor description"},"id":{"type":"string","format":"string"},"name":{"type":"string","description":"Vendor name"},"organization_id":{"type":"string","format":"string"},"updated_at":{"type":"string","description":"Update timestamp","format":"date-time"}}}}}}`)
	UpdateVendorToolInputSchema       = mcp.MustUnmarshalSchema(`{"type":"object","required":["id"],"properties":{"description":{"type":"string","description":"Vendor description"},"id":{"type":"string","format":"string"},"name":{"type":"string","description":"Vendor name"}}}`)
	UpdateVendorToolOutputSchema      = mcp.MustUnmarshalSchema(`{"type":"object","required":["vendor"],"properties":{"vendor":{"type":"object","required":["id","name","organization_id","created_at","updated_at"],"properties":{"created_at":{"type":"string","description":"Creation timestamp","format":"date-time"},"description":{"description":"Vendor description"},"id":{"type":"string","format":"string"},"name":{"type":"string","description":"Vendor name"},"organization_id":{"type":"string","format":"string"},"updated_at":{"type":"string","description":"Update timestamp","format":"date-time"}}}}}`)
)

// AddVendorInput represents the schema
type AddVendorInput struct {
	// Creation timestamp
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// Vendor description
	Description *string `json:"description,omitempty"`
	// Vendor name
	Name string `json:"name"`
	// Organization ID
	OrganizationID gid.GID `json:"organization_id"`
	// Update timestamp
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// AddVendorOutput represents the schema
type AddVendorOutput struct {
	Vendor *Vendor `json:"vendor"`
}

// ListOrganizationsInput represents the schema
type ListOrganizationsInput struct {
	// Organization ID
	OrganizationID *gid.GID `json:"organization_id,omitempty"`
}

// ListOrganizationsOutput represents the schema
type ListOrganizationsOutput struct {
	Organizations []*Organization `json:"organizations,omitempty"`
}

// ListVendorsInput represents the schema
type ListVendorsInput struct {
	// Page cursor
	Cursor *page.CursorKey         `json:"cursor,omitempty"`
	Filter *ListVendorsInputFilter `json:"filter,omitempty"`
	// Vendor order by
	OrderBy *VendorOrderBy `json:"order_by,omitempty"`
	// Organization ID
	OrganizationID gid.GID `json:"organization_id"`
	// Page size
	Size *int64 `json:"size,omitempty"`
}

// ListVendorsOutput represents the schema
type ListVendorsOutput struct {
	// Next cursor
	NextCursor *page.CursorKey `json:"next_cursor,omitempty"`
	Vendors    []*Vendor       `json:"vendors"`
}

// Organization represents the schema
type Organization struct {
	// Creation timestamp
	CreatedAt time.Time `json:"created_at"`
	// Organization description
	Description *string `json:"description"`
	// Organization ID
	ID gid.GID `json:"id"`
	// Organization name
	Name string `json:"name"`
	// Update timestamp
	UpdatedAt time.Time `json:"updated_at"`
}

// UpdateVendorInput represents the schema
type UpdateVendorInput struct {
	// Vendor description
	Description *string `json:"description,omitempty"`
	// Vendor ID
	ID gid.GID `json:"id"`
	// Vendor name
	Name *string `json:"name,omitempty"`
}

// UpdateVendorOutput represents the schema
type UpdateVendorOutput struct {
	Vendor *Vendor `json:"vendor"`
}

// Vendor represents the schema
type Vendor struct {
	// Creation timestamp
	CreatedAt time.Time `json:"created_at"`
	// Vendor description
	Description *string `json:"description,omitempty"`
	// Vendor ID
	ID gid.GID `json:"id"`
	// Vendor name
	Name string `json:"name"`
	// Organization ID
	OrganizationID gid.GID `json:"organization_id"`
	// Update timestamp
	UpdatedAt time.Time `json:"updated_at"`
}

// VendorOrderBy represents the schema
type VendorOrderBy struct {
	// Vendor order direction
	Direction page.OrderDirection `json:"direction"`
	// Vendor order field
	Field coredata.VendorOrderField `json:"field"`
}

// ListVendorsInputFilter represents the schema
type ListVendorsInputFilter struct {
	// Snapshot ID
	SnapshotID *gid.GID `json:"snapshot_id,omitempty"`
}
