// Copyright (c) 2026 Probo Inc <hello@probo.com>.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package console_v1

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"go.gearno.de/kit/log"
	"go.probo.inc/probo/pkg/accessreview/drivers"
	"go.probo.inc/probo/pkg/connector"
	"go.probo.inc/probo/pkg/coredata"
	"go.probo.inc/probo/pkg/server/api/console/v1/types"
	"go.probo.inc/probo/pkg/server/gqlutils"
)

// These helpers live outside connector_resolvers.go because that file is
// regenerated by gqlgen, which does not preserve standalone functions.

// resolveAPIKeyConnectorCredential returns the API key to persist on a new
// API-key connection. For ManagedAPIKey providers (Model B, e.g. Crisp) it
// persists NOTHING (empty string): the Probo-held key is resolved at
// use time by (*provider.Registry).APIKeyFor, so it survives key
// rotation and is not duplicated across tenant rows. It still requires the
// key to be configured, which is what keeps the provider deactivated, and
// ignores any client-supplied value. For all other providers it requires
// the client-supplied key. The returned error is surfaced verbatim to the
// client via gqlutils.Invalid, so it contains only provider/field names,
// never the key itself.
func (r *Resolver) resolveAPIKeyConnectorCredential(provider coredata.ConnectorProvider, clientKey *string) (string, error) {
	if reg, ok := r.providerRegistry.Get(provider); ok && reg.IsManagedAPIKey() {
		if _, ok := r.providerRegistry.ManagedAPIKey(provider); !ok {
			return "", fmt.Errorf("connector is not configured for this deployment")
		}

		return "", nil
	}

	if clientKey == nil || strings.TrimSpace(*clientKey) == "" {
		return "", fmt.Errorf("apiKey is required")
	}

	// A key is copied out of a provider's UI, so it arrives with whatever the
	// clipboard picked up. Several transports encode the credential verbatim,
	// where a trailing newline is an authentication failure the customer has
	// no way to see.
	key := strings.TrimSpace(*clientKey)

	if err := r.providerRegistry.ValidateAPIKey(provider, key); err != nil {
		return "", err
	}

	return key, nil
}

// newAPIKeyConnection builds an API-key connection for provider, filling the auth
// presentation (header, basic-auth mode, scheme) from the provider registry and
// using key as the credential. Both CreateAPIKeyConnector (the persisted
// connection) and the pre-write validation clients (resolveTallySettings) build
// their connection through it, so a key accepted at validation time
// authenticates exactly as the persisted connector will: a new auth flag cannot
// be added to one path and silently missed on the other.
func (r *Resolver) newAPIKeyConnection(provider coredata.ConnectorProvider, key string) *connector.APIKeyConnection {
	return r.providerRegistry.NewAPIKeyConnection(provider, key)
}

// tallyUserFetcher fetches the Tally user profile bound to an API key. It
// matches drivers.GetTallyCurrentUser: resolveTallySettings injects the real
// fetch, and tests substitute a fake so the branch wiring (the auth-failure
// mapping and the derived organization id) is exercised without a live
// Tally API.
type tallyUserFetcher func(ctx context.Context, httpClient *http.Client, baseURL string) (*drivers.TallyCurrentUser, error)

// resolveTallySettings validates the presented API key against Tally and
// derives the connector settings from it: GET /users/me both proves the key
// is accepted and returns the organization it belongs to, so no
// organization-id input is asked of the user (Tally 401s a wrong org id,
// indistinguishable from a bad key). Runs before any write, so a rejected
// key leaves no row. Returned Invalid errors carry only guidance, never the
// key.
func (r *Resolver) resolveTallySettings(ctx context.Context, apiKey string) (json.RawMessage, error) {
	return r.resolveTallySettingsWith(ctx, apiKey, drivers.GetTallyCurrentUser)
}

// resolveTallySettingsWith is resolveTallySettings with the profile fetch
// injected, so its branch wiring can be unit-tested without reaching the
// live Tally API. resolveTallySettings passes the real
// drivers.GetTallyCurrentUser.
func (r *Resolver) resolveTallySettingsWith(ctx context.Context, apiKey string, fetch tallyUserFetcher) (json.RawMessage, error) {
	reg, ok := r.providerRegistry.Get(coredata.ConnectorProviderTally)
	if !ok {
		r.logger.ErrorCtx(ctx, "tally connector provider not registered")

		return nil, gqlutils.Internal(ctx)
	}

	// The validation client authenticates exactly as the persisted connector
	// will, so a key accepted here keeps working for the workers.
	conn := r.newAPIKeyConnection(coredata.ConnectorProviderTally, apiKey)

	httpClient, err := conn.Client(ctx)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot build tally validation client", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	user, err := fetch(ctx, httpClient, reg.Endpoints.APIBase)

	switch {
	case errors.Is(err, drivers.ErrTallyUnauthorized):
		return nil, gqlutils.Invalidf(ctx, "Tally rejected the API key: create a key under Settings > API keys and try again")
	case err != nil:
		r.logger.ErrorCtx(ctx, "cannot fetch tally current user", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	if user.OrganizationID == "" {
		r.logger.ErrorCtx(ctx, "tally current user has no organization id")

		return nil, gqlutils.Internal(ctx)
	}

	return json.Marshal(&coredata.TallyConnectorSettings{OrganizationID: user.OrganizationID})
}

// apiKeyConnectorSettings marshals the provider-specific extra settings
// for an API-key connector from the typed gqlgen input into the JSON
// blob persisted on coredata.Connector.RawSettings. It returns (nil,
// nil) for providers without extra settings.
//
// Returned errors are surfaced verbatim to the client via
// gqlutils.Invalid: they must contain only field names and structural
// information, never user-supplied values.
func apiKeyConnectorSettings(input types.CreateAPIKeyConnectorInput) (json.RawMessage, error) {
	switch input.Provider {
	case coredata.ConnectorProviderSentry:
		if input.SentryOrganizationSlug == nil || *input.SentryOrganizationSlug == "" {
			return nil, fmt.Errorf("cannot create sentry connector: sentryOrganizationSlug is required")
		}

		return json.Marshal(&coredata.SentryConnectorSettings{OrganizationSlug: *input.SentryOrganizationSlug})
	case coredata.ConnectorProviderSupabase:
		if input.SupabaseOrganizationSlug == nil || *input.SupabaseOrganizationSlug == "" {
			return nil, fmt.Errorf("cannot create supabase connector: supabaseOrganizationSlug is required")
		}

		return json.Marshal(&coredata.SupabaseConnectorSettings{OrganizationSlug: *input.SupabaseOrganizationSlug})
	case coredata.ConnectorProviderGitHub:
		if input.GithubOrganization == nil || *input.GithubOrganization == "" {
			return nil, fmt.Errorf("cannot create github connector: githubOrganization is required")
		}

		return json.Marshal(&coredata.GitHubConnectorSettings{Organization: *input.GithubOrganization})
	case coredata.ConnectorProviderGrafana:
		if input.GrafanaBaseURL == nil || *input.GrafanaBaseURL == "" {
			return nil, fmt.Errorf("cannot create grafana connector: grafanaBaseUrl is required")
		}

		u, err := url.Parse(*input.GrafanaBaseURL)
		if err != nil || (u.Scheme != "http" && u.Scheme != "https") || u.Host == "" {
			return nil, fmt.Errorf("cannot create grafana connector: grafanaBaseUrl must be an http(s) URL")
		}

		return json.Marshal(&coredata.GrafanaConnectorSettings{BaseURL: *input.GrafanaBaseURL})
	case coredata.ConnectorProviderSigNoz:
		if input.SignozBaseURL == nil || *input.SignozBaseURL == "" {
			return nil, fmt.Errorf("cannot create signoz connector: signozBaseUrl is required")
		}

		u, err := url.Parse(*input.SignozBaseURL)
		if err != nil || (u.Scheme != "http" && u.Scheme != "https") || u.Host == "" {
			return nil, fmt.Errorf("cannot create signoz connector: signozBaseUrl must be an http(s) URL")
		}

		return json.Marshal(&coredata.SigNozConnectorSettings{BaseURL: *input.SignozBaseURL})
	case coredata.ConnectorProviderNewRelic:
		if input.NewRelicRegion == nil || *input.NewRelicRegion == "" {
			return nil, fmt.Errorf("cannot create new relic connector: newRelicRegion is required")
		}

		// The region selects which of New Relic's three NerdGraph endpoints
		// the driver talks to, so it goes into a URL: accept only the three
		// the driver knows and reject anything else here rather than at first use.
		if _, err := drivers.NewRelicEndpoint(*input.NewRelicRegion); err != nil {
			return nil, fmt.Errorf("cannot create new relic connector: newRelicRegion must be us, eu or jp")
		}

		// Stored normalized so one region is not persisted as "eu", "EU" and
		// "  eu  " and re-normalized on every read.
		return json.Marshal(&coredata.NewRelicConnectorSettings{
			Region: strings.ToLower(strings.TrimSpace(*input.NewRelicRegion)),
		})
	case coredata.ConnectorProviderTwingate:
		if input.TwingateNetwork == nil || *input.TwingateNetwork == "" {
			return nil, fmt.Errorf("cannot create twingate connector: twingateNetwork is required")
		}

		// TwingateNetwork returns the canonical label, so the value stored is
		// the one the host is built from rather than whatever was typed.
		network, err := drivers.TwingateNetwork(*input.TwingateNetwork)
		if err != nil {
			return nil, fmt.Errorf("cannot create twingate connector: twingateNetwork must be a valid network name")
		}

		return json.Marshal(&coredata.TwingateConnectorSettings{Network: network})
	case coredata.ConnectorProviderRetool:
		// Optional: Retool Cloud routes every organization through the shared
		// api.retool.com gateway, so only a self-hosted customer has a URL to
		// give. An empty setting is the cloud case, not a missing field.
		if input.RetoolBaseURL == nil || *input.RetoolBaseURL == "" {
			return json.Marshal(&coredata.RetoolConnectorSettings{})
		}

		u, err := url.Parse(*input.RetoolBaseURL)
		if err != nil || (u.Scheme != "http" && u.Scheme != "https") || u.Hostname() == "" {
			return nil, fmt.Errorf("cannot create retool connector: retoolBaseUrl must be an http(s) URL")
		}

		return json.Marshal(&coredata.RetoolConnectorSettings{BaseURL: *input.RetoolBaseURL})
	case coredata.ConnectorProviderAuthentik:
		if input.AuthentikBaseURL == nil || *input.AuthentikBaseURL == "" {
			return nil, fmt.Errorf("cannot create authentik connector: authentikBaseUrl is required")
		}

		u, err := url.Parse(*input.AuthentikBaseURL)
		if err != nil || (u.Scheme != "http" && u.Scheme != "https") || u.Hostname() == "" {
			return nil, fmt.Errorf("cannot create authentik connector: authentikBaseUrl must be an http(s) URL")
		}

		return json.Marshal(&coredata.AuthentikConnectorSettings{BaseURL: *input.AuthentikBaseURL})
	case coredata.ConnectorProviderOnePassword:
		if input.OnePasswordScimBridgeURL == nil || *input.OnePasswordScimBridgeURL == "" {
			return nil, fmt.Errorf("cannot create 1password connector: onePasswordScimBridgeURL is required")
		}

		u, err := url.Parse(*input.OnePasswordScimBridgeURL)
		if err != nil || (u.Scheme != "http" && u.Scheme != "https") || u.Host == "" {
			return nil, fmt.Errorf("cannot create 1password connector: onePasswordScimBridgeURL must be an http(s) URL")
		}

		return json.Marshal(&coredata.OnePasswordConnectorSettings{SCIMBridgeURL: *input.OnePasswordScimBridgeURL})
	case coredata.ConnectorProviderMetabase:
		if input.MetabaseInstanceURL == nil || *input.MetabaseInstanceURL == "" {
			return nil, fmt.Errorf("cannot create metabase connector: metabaseInstanceUrl is required")
		}

		u, err := url.Parse(*input.MetabaseInstanceURL)
		if err != nil || (u.Scheme != "http" && u.Scheme != "https") || u.Host == "" {
			return nil, fmt.Errorf("cannot create metabase connector: metabaseInstanceUrl must be an http(s) URL")
		}

		return json.Marshal(&coredata.MetabaseConnectorSettings{InstanceURL: *input.MetabaseInstanceURL})
	case coredata.ConnectorProviderPostHog:
		region := ""
		if input.PosthogRegion != nil {
			region = *input.PosthogRegion
		}

		instanceURL := ""
		if input.PosthogInstanceURL != nil {
			instanceURL = *input.PosthogInstanceURL
		}

		// Cloud (region) and self-hosted (instance URL) are mutually
		// exclusive; exactly one identifies the connection's data host.
		switch {
		case region != "" && instanceURL != "":
			return nil, fmt.Errorf("cannot create posthog connector: set either posthogRegion or posthogInstanceUrl, not both")
		case region != "":
			baseURL, ok := drivers.PostHogRegionBaseURL(region)
			if !ok {
				return nil, fmt.Errorf("cannot create posthog connector: posthogRegion must be US or EU")
			}

			return json.Marshal(&coredata.PostHogConnectorSettings{BaseURL: baseURL})
		case instanceURL != "":
			u, err := url.Parse(instanceURL)
			if err != nil || (u.Scheme != "http" && u.Scheme != "https") || u.Host == "" {
				return nil, fmt.Errorf("cannot create posthog connector: posthogInstanceUrl must be an http(s) URL")
			}

			return json.Marshal(&coredata.PostHogConnectorSettings{BaseURL: instanceURL})
		default:
			return nil, fmt.Errorf("cannot create posthog connector: posthogRegion or posthogInstanceUrl is required")
		}
	case coredata.ConnectorProviderOkta:
		if input.OktaDomain == nil || *input.OktaDomain == "" {
			return nil, fmt.Errorf("cannot create okta connector: oktaDomain is required")
		}

		// NormalizeOktaDomain strips scheme/path and validates the host; the
		// stored value is the bare org domain (e.g. "acme.okta.com"). Use a
		// static error message — this string is surfaced verbatim to the
		// client and must never echo the operator-supplied input.
		domain, err := connector.NormalizeOktaDomain(*input.OktaDomain)
		if err != nil {
			return nil, fmt.Errorf("cannot create okta connector: oktaDomain must be a valid Okta domain (e.g. acme.okta.com)")
		}

		return json.Marshal(&coredata.OktaConnectorSettings{Domain: domain})
	case coredata.ConnectorProviderBetterStack:
		if input.BetterStackTeamName == nil || *input.BetterStackTeamName == "" {
			return nil, fmt.Errorf("cannot create better stack connector: betterStackTeamName is required")
		}

		return json.Marshal(&coredata.BetterStackConnectorSettings{TeamName: *input.BetterStackTeamName})
	case coredata.ConnectorProviderQovery:
		if input.QoveryOrganizationID == nil || *input.QoveryOrganizationID == "" {
			return nil, fmt.Errorf("cannot create qovery connector: qoveryOrganizationId is required")
		}

		return json.Marshal(&coredata.QoveryConnectorSettings{OrganizationID: *input.QoveryOrganizationID})
	case coredata.ConnectorProviderRender:
		if input.RenderWorkspaceID == nil || *input.RenderWorkspaceID == "" {
			return nil, fmt.Errorf("cannot create render connector: renderWorkspaceId is required")
		}

		return json.Marshal(&coredata.RenderConnectorSettings{OwnerID: *input.RenderWorkspaceID})
	case coredata.ConnectorProviderNeon:
		if input.NeonOrganizationID == nil || *input.NeonOrganizationID == "" {
			return nil, fmt.Errorf("cannot create neon connector: neonOrganizationId is required")
		}

		return json.Marshal(&coredata.NeonConnectorSettings{OrganizationID: *input.NeonOrganizationID})
	case coredata.ConnectorProviderLangfuse:
		if input.LangfuseBaseURL == nil || *input.LangfuseBaseURL == "" {
			return nil, fmt.Errorf("cannot create langfuse connector: langfuseBaseUrl is required")
		}

		u, err := url.Parse(*input.LangfuseBaseURL)
		if err != nil || (u.Scheme != "http" && u.Scheme != "https") || u.Host == "" {
			return nil, fmt.Errorf("cannot create langfuse connector: langfuseBaseUrl must be an http(s) URL")
		}

		return json.Marshal(&coredata.LangfuseConnectorSettings{BaseURL: *input.LangfuseBaseURL})
	case coredata.ConnectorProviderScaleway:
		if input.ScalewayOrganizationID == nil || *input.ScalewayOrganizationID == "" {
			return nil, fmt.Errorf("cannot create scaleway connector: scalewayOrganizationId is required")
		}

		return json.Marshal(&coredata.ScalewayConnectorSettings{OrganizationID: *input.ScalewayOrganizationID})
	case coredata.ConnectorProviderSegment:
		region := ""
		if input.SegmentRegion != nil {
			region = strings.ToUpper(strings.TrimSpace(*input.SegmentRegion))
		}

		// The region selects the API host and is not discoverable from the
		// token; resolve it to a base URL against a fixed allow-list so an
		// unexpected value cannot reach the driver.
		var baseURL string

		switch region {
		case "US":
			baseURL = "https://api.segmentapis.com"
		case "EU":
			baseURL = "https://eu1.api.segmentapis.com"
		default:
			return nil, fmt.Errorf("cannot create segment connector: segmentRegion must be US or EU")
		}

		return json.Marshal(&coredata.SegmentConnectorSettings{BaseURL: baseURL})
	}

	return nil, nil
}

// clientCredentialsConnectorSettings marshals the provider-specific
// extra settings for a client-credentials connector. See
// apiKeyConnectorSettings for the error contract.
func clientCredentialsConnectorSettings(input types.CreateClientCredentialsConnectorInput) (json.RawMessage, error) {
	switch input.Provider {
	case coredata.ConnectorProviderOnePassword:
		if input.OnePasswordAccountID == nil || *input.OnePasswordAccountID == "" ||
			input.OnePasswordRegion == nil || *input.OnePasswordRegion == "" {
			return nil, fmt.Errorf("cannot create 1password connector: onePasswordAccountId and onePasswordRegion are required")
		}

		return json.Marshal(&coredata.OnePasswordUsersAPISettings{
			AccountID: *input.OnePasswordAccountID,
			Region:    *input.OnePasswordRegion,
		})
	}

	return nil, nil
}
