package console_v1

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"

	"go.gearno.de/kit/log"
	"go.probo.inc/probo/pkg/coredata"
	"go.probo.inc/probo/pkg/probo"
	"go.probo.inc/probo/pkg/server/api/console/v1/schema"
	"go.probo.inc/probo/pkg/server/api/console/v1/types"
	"go.probo.inc/probo/pkg/server/gqlutils"
)

// CookieBanner is the resolver for the cookieBanner field.
func (r *cookieConsentRecordResolver) CookieBanner(ctx context.Context, obj *types.CookieConsentRecord) (*types.CookieBanner, error) {
	return obj.CookieBanner, nil
}

// CookieBannerVersion is the resolver for the cookieBannerVersion field.
func (r *cookieConsentRecordResolver) CookieBannerVersion(ctx context.Context, obj *types.CookieConsentRecord) (*types.CookieBannerVersion, error) {
	return obj.CookieBannerVersion, nil
}

// TotalCount is the resolver for the totalCount field.
func (r *cookieConsentRecordConnectionResolver) TotalCount(ctx context.Context, obj *types.CookieConsentRecordConnection) (int, error) {
	if err := r.authorize(ctx, obj.ParentID, probo.ActionCookieConsentRecordList); err != nil {
		return 0, err
	}

	scope := coredata.NewScopeFromObjectID(obj.ParentID)

	count, err := r.cookieBanner.CountCookieConsentRecordsForBanner(ctx, scope, obj.ParentID, obj.Filter)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot count consent records", log.Error(err))
		return 0, gqlutils.Internal(ctx)
	}

	return count, nil
}

// CookieConsentRecord returns schema.CookieConsentRecordResolver implementation.
func (r *Resolver) CookieConsentRecord() schema.CookieConsentRecordResolver {
	return &cookieConsentRecordResolver{r}
}

// CookieConsentRecordConnection returns schema.CookieConsentRecordConnectionResolver implementation.
func (r *Resolver) CookieConsentRecordConnection() schema.CookieConsentRecordConnectionResolver {
	return &cookieConsentRecordConnectionResolver{r}
}

type cookieConsentRecordResolver struct{ *Resolver }
type cookieConsentRecordConnectionResolver struct{ *Resolver }
