package console_v1

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"time"

	"go.gearno.de/kit/log"
	"go.probo.inc/probo/pkg/itam"
	"go.probo.inc/probo/pkg/server/api/console/v1/schema"
	"go.probo.inc/probo/pkg/server/api/console/v1/types"
	"go.probo.inc/probo/pkg/server/gqlutils"
)

// LatestPostures is the resolver for the Device.latestPostures field.
func (r *deviceResolver) LatestPostures(ctx context.Context, obj *types.Device) ([]*types.DevicePosture, error) {
	scope, err := r.authorize(ctx, obj.ID, itam.ActionDevicePostureList)
	if err != nil {
		return nil, err
	}

	postures, err := r.itam.GetLatestPostures(ctx, scope, obj.ID)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot load latest device postures", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return types.NewDevicePostures(postures), nil
}

// TotalCount is the resolver for the DeviceConnection.totalCount field.
func (r *deviceConnectionResolver) TotalCount(ctx context.Context, obj *types.DeviceConnection) (int, error) {
	scope, err := r.authorize(ctx, obj.ParentID, itam.ActionDeviceList)
	if err != nil {
		return 0, err
	}

	switch obj.Resolver.(type) {
	case *organizationResolver:
		return r.itam.CountForOrganizationID(ctx, scope, obj.ParentID)
	}

	return 0, gqlutils.Internal(ctx)
}

// CreateDeviceEnrollmentToken is the resolver for the createDeviceEnrollmentToken field.
func (r *mutationResolver) CreateDeviceEnrollmentToken(ctx context.Context, input types.CreateDeviceEnrollmentTokenInput) (*types.CreateDeviceEnrollmentTokenPayload, error) {
	scope, err := r.authorize(ctx, input.OrganizationID, itam.ActionDeviceEnrollmentTokenCreate)
	if err != nil {
		return nil, err
	}

	validity := time.Duration(0)
	if input.ValiditySeconds != nil && *input.ValiditySeconds > 0 {
		validity = time.Duration(*input.ValiditySeconds) * time.Second
	}

	result, err := r.itam.CreateEnrollmentToken(ctx, scope, itam.CreateEnrollmentTokenRequest{
		OrganizationID: input.OrganizationID,
		Name:           input.Name,
		Validity:       validity,
		MaxUses:        input.MaxUses,
	})
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot create device enrollment token", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return &types.CreateDeviceEnrollmentTokenPayload{
		EnrollmentToken: types.NewDeviceEnrollmentToken(result.Token),
		Secret:          result.Secret,
	}, nil
}

// RevokeDeviceEnrollmentToken is the resolver for the revokeDeviceEnrollmentToken field.
func (r *mutationResolver) RevokeDeviceEnrollmentToken(ctx context.Context, input types.RevokeDeviceEnrollmentTokenInput) (*types.RevokeDeviceEnrollmentTokenPayload, error) {
	scope, err := r.authorize(ctx, input.EnrollmentTokenID, itam.ActionDeviceEnrollmentTokenRevoke)
	if err != nil {
		return nil, err
	}

	token, err := r.itam.RevokeEnrollmentToken(ctx, scope, input.EnrollmentTokenID)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot revoke device enrollment token", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return &types.RevokeDeviceEnrollmentTokenPayload{
		EnrollmentToken: types.NewDeviceEnrollmentToken(token),
	}, nil
}

// RevokeDevice is the resolver for the revokeDevice field.
func (r *mutationResolver) RevokeDevice(ctx context.Context, input types.RevokeDeviceInput) (*types.RevokeDevicePayload, error) {
	scope, err := r.authorize(ctx, input.DeviceID, itam.ActionDeviceRevoke)
	if err != nil {
		return nil, err
	}

	d, err := r.itam.RevokeDevice(ctx, scope, input.DeviceID)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot revoke device", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return &types.RevokeDevicePayload{Device: types.NewDevice(d)}, nil
}

// AssignDeviceToUser is the resolver for the assignDeviceToUser field.
func (r *mutationResolver) AssignDeviceToUser(ctx context.Context, input types.AssignDeviceToUserInput) (*types.AssignDeviceToUserPayload, error) {
	scope, err := r.authorize(ctx, input.DeviceID, itam.ActionDeviceAssign)
	if err != nil {
		return nil, err
	}

	d, err := r.itam.AssignDeviceToUser(ctx, scope, input.DeviceID, input.UserIdentityID)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot assign device to user", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return &types.AssignDeviceToUserPayload{Device: types.NewDevice(d)}, nil
}

// Device returns schema.DeviceResolver implementation.
func (r *Resolver) Device() schema.DeviceResolver { return &deviceResolver{r} }

// DeviceConnection returns schema.DeviceConnectionResolver implementation.
func (r *Resolver) DeviceConnection() schema.DeviceConnectionResolver {
	return &deviceConnectionResolver{r}
}

type deviceResolver struct{ *Resolver }
type deviceConnectionResolver struct{ *Resolver }
