package console_v1

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"errors"

	"go.gearno.de/kit/log"
	"go.probo.inc/probo/pkg/coredata"
	employeeportalmgmt "go.probo.inc/probo/pkg/employeeportal/management"
	"go.probo.inc/probo/pkg/probo"
	"go.probo.inc/probo/pkg/server/api/console/v1/schema"
	"go.probo.inc/probo/pkg/server/api/console/v1/types"
	"go.probo.inc/probo/pkg/server/gqlutils"
	"go.probo.inc/probo/pkg/validator"
)

// Logo is the resolver for the logo field.
func (r *employeePortalResolver) Logo(ctx context.Context, obj *types.EmployeePortal) (*types.File, error) {
	if _, err := r.authorize(ctx, obj.ID, employeeportalmgmt.ActionEmployeePortalGet); err != nil {
		return nil, err
	}

	if obj.Logo == nil {
		return nil, nil
	}

	return r.loadFile(ctx, obj.Logo.ID)
}

// DarkLogo is the resolver for the darkLogo field.
func (r *employeePortalResolver) DarkLogo(ctx context.Context, obj *types.EmployeePortal) (*types.File, error) {
	if _, err := r.authorize(ctx, obj.ID, employeeportalmgmt.ActionEmployeePortalGet); err != nil {
		return nil, err
	}

	if obj.DarkLogo == nil {
		return nil, nil
	}

	return r.loadFile(ctx, obj.DarkLogo.ID)
}

// Organization is the resolver for the organization field.
func (r *employeePortalResolver) Organization(ctx context.Context, obj *types.EmployeePortal) (*types.Organization, error) {
	if obj.Organization == nil {
		r.logger.ErrorCtx(ctx, "employee portal is missing organization id")
		return nil, gqlutils.Internal(ctx)
	}

	scope, err := r.authorize(ctx, obj.Organization.ID, probo.ActionOrganizationGet)
	if err != nil {
		return nil, err
	}

	organization, err := r.probo.Organizations.Get(ctx, scope, obj.Organization.ID)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot get organization", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return types.NewOrganization(organization), nil
}

// Permission is the resolver for the permission field.
func (r *employeePortalResolver) Permission(ctx context.Context, obj *types.EmployeePortal, action string) (bool, error) {
	return r.Resolver.Permission(ctx, obj, action)
}

// TotalCount is the resolver for the totalCount field.
func (r *employeePortalConnectionResolver) TotalCount(ctx context.Context, obj *types.EmployeePortalConnection) (int, error) {
	scope, err := r.authorize(ctx, obj.ParentID, employeeportalmgmt.ActionEmployeePortalList)
	if err != nil {
		return 0, err
	}

	count, err := r.employeePortal.CountForOrganizationID(ctx, scope, obj.ParentID)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot count employee portals", log.Error(err))

		return 0, gqlutils.Internal(ctx)
	}

	return count, nil
}

// CreateEmployeePortal is the resolver for the createEmployeePortal field.
func (r *mutationResolver) CreateEmployeePortal(ctx context.Context, input types.CreateEmployeePortalInput) (*types.CreateEmployeePortalPayload, error) {
	scope, err := r.authorize(ctx, input.OrganizationID, employeeportalmgmt.ActionEmployeePortalCreate)
	if err != nil {
		return nil, err
	}

	portal, err := r.employeePortal.Create(
		ctx,
		scope,
		&employeeportalmgmt.CreateEmployeePortalRequest{
			OrganizationID: input.OrganizationID,
			Name:           input.Name,
		},
	)
	if err != nil {
		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		r.logger.ErrorCtx(ctx, "cannot create employee portal", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.CreateEmployeePortalPayload{
		EmployeePortalEdge: types.NewEmployeePortalEdge(portal, coredata.EmployeePortalOrderFieldCreatedAt),
	}, nil
}

// UpdateEmployeePortal is the resolver for the updateEmployeePortal field.
func (r *mutationResolver) UpdateEmployeePortal(ctx context.Context, input types.UpdateEmployeePortalInput) (*types.UpdateEmployeePortalPayload, error) {
	scope, err := r.authorize(ctx, input.EmployeePortalID, employeeportalmgmt.ActionEmployeePortalUpdate)
	if err != nil {
		return nil, err
	}

	var capabilities *coredata.EmployeePortalCapabilitiesPatch
	if input.Capabilities != nil {
		capabilities = &coredata.EmployeePortalCapabilitiesPatch{
			DeviceAgent: input.Capabilities.DeviceAgent,
		}
	}

	portal, err := r.employeePortal.Update(
		ctx,
		scope,
		&employeeportalmgmt.UpdateRequest{
			ID:           input.EmployeePortalID,
			Name:         input.Name,
			Active:       input.Active,
			Capabilities: capabilities,
		},
	)
	if err != nil {
		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		r.logger.ErrorCtx(ctx, "cannot update employee portal", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.UpdateEmployeePortalPayload{
		EmployeePortal: types.NewEmployeePortal(portal),
	}, nil
}

// UpdateEmployeePortalBrand is the resolver for the updateEmployeePortalBrand field.
func (r *mutationResolver) UpdateEmployeePortalBrand(ctx context.Context, input types.UpdateEmployeePortalBrandInput) (*types.UpdateEmployeePortalBrandPayload, error) {
	scope, err := r.authorize(ctx, input.EmployeePortalID, employeeportalmgmt.ActionEmployeePortalUploadBrand)
	if err != nil {
		return nil, err
	}

	req := &employeeportalmgmt.UpdateBrandRequest{
		EmployeePortalID: input.EmployeePortalID,
	}

	if input.LogoFile.IsSet() {
		logoFile := input.LogoFile.Value()
		if logoFile == nil {
			var nilFile *employeeportalmgmt.FileUpload

			req.LogoFile = &nilFile
		} else {
			fileUpload := &employeeportalmgmt.FileUpload{
				Content:     logoFile.File,
				Filename:    logoFile.Filename,
				Size:        logoFile.Size,
				ContentType: logoFile.ContentType,
			}
			req.LogoFile = &fileUpload
		}
	}

	if input.DarkLogoFile.IsSet() {
		darkLogoFile := input.DarkLogoFile.Value()
		if darkLogoFile == nil {
			var nilFile *employeeportalmgmt.FileUpload

			req.DarkLogoFile = &nilFile
		} else {
			fileUpload := &employeeportalmgmt.FileUpload{
				Content:     darkLogoFile.File,
				Filename:    darkLogoFile.Filename,
				Size:        darkLogoFile.Size,
				ContentType: darkLogoFile.ContentType,
			}
			req.DarkLogoFile = &fileUpload
		}
	}

	portal, err := r.employeePortal.UpdateBrand(ctx, scope, req)
	if err != nil {
		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		r.logger.ErrorCtx(ctx, "cannot update employee portal brand", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.UpdateEmployeePortalBrandPayload{
		EmployeePortal: types.NewEmployeePortal(portal),
	}, nil
}

// DeleteEmployeePortal is the resolver for the deleteEmployeePortal field.
func (r *mutationResolver) DeleteEmployeePortal(ctx context.Context, input types.DeleteEmployeePortalInput) (*types.DeleteEmployeePortalPayload, error) {
	scope, err := r.authorize(ctx, input.EmployeePortalID, employeeportalmgmt.ActionEmployeePortalDelete)
	if err != nil {
		return nil, err
	}

	if err := r.employeePortal.Delete(ctx, scope, input.EmployeePortalID); err != nil {
		r.logger.ErrorCtx(ctx, "cannot delete employee portal", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.DeleteEmployeePortalPayload{
		DeletedEmployeePortalID: input.EmployeePortalID,
	}, nil
}

// EmployeePortal returns schema.EmployeePortalResolver implementation.
func (r *Resolver) EmployeePortal() schema.EmployeePortalResolver { return &employeePortalResolver{r} }

// EmployeePortalConnection returns schema.EmployeePortalConnectionResolver implementation.
func (r *Resolver) EmployeePortalConnection() schema.EmployeePortalConnectionResolver {
	return &employeePortalConnectionResolver{r}
}

type (
	employeePortalResolver           struct{ *Resolver }
	employeePortalConnectionResolver struct{ *Resolver }
)
