package console_v1

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"encoding/json"
	"errors"
	"time"

	"go.gearno.de/kit/log"
	"go.probo.inc/probo/pkg/coredata"
	"go.probo.inc/probo/pkg/page"
	"go.probo.inc/probo/pkg/probo"
	"go.probo.inc/probo/pkg/riskmanagement"
	"go.probo.inc/probo/pkg/server/api/authn"
	"go.probo.inc/probo/pkg/server/api/console/v1/schema"
	"go.probo.inc/probo/pkg/server/api/console/v1/types"
	"go.probo.inc/probo/pkg/server/gqlutils"
	"go.probo.inc/probo/pkg/task"
	"go.probo.inc/probo/pkg/validator"
)

// Owner is the resolver for the owner field.
func (r *internalControlResolver) Owner(ctx context.Context, obj *types.InternalControl) (*types.Profile, error) {
	return r.loadProfile(ctx, obj.Owner)
}

// Reviewer is the resolver for the reviewer field.
func (r *internalControlResolver) Reviewer(ctx context.Context, obj *types.InternalControl) (*types.Profile, error) {
	return r.loadProfile(ctx, obj.Reviewer)
}

// Evidences is the resolver for the evidences field.
func (r *internalControlResolver) Evidences(ctx context.Context, obj *types.InternalControl, first *int, after *page.CursorKey, last *int, before *page.CursorKey, orderBy *types.EvidenceOrderBy) (*types.EvidenceConnection, error) {
	scope, err := r.authorize(ctx, obj.ID, probo.ActionEvidenceList)
	if err != nil {
		return nil, err
	}

	pageOrderBy := page.OrderBy[coredata.EvidenceOrderField]{
		Field:     coredata.EvidenceOrderFieldCreatedAt,
		Direction: page.OrderDirectionDesc,
	}

	if orderBy != nil {
		pageOrderBy = page.OrderBy[coredata.EvidenceOrderField]{
			Field:     orderBy.Field,
			Direction: orderBy.Direction,
		}
	}

	cursor := types.NewCursor(first, after, last, before, pageOrderBy)

	page, err := r.probo.Evidences.ListForInternalControlID(ctx, scope, obj.ID, cursor)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot list internal control evidences", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return types.NewEvidenceConnection(page, r, obj.ID), nil
}

// Tasks is the resolver for the tasks field.
func (r *internalControlResolver) Tasks(ctx context.Context, obj *types.InternalControl, first *int, after *page.CursorKey, last *int, before *page.CursorKey, orderBy *types.TaskOrderBy, filter *types.TaskFilter) (*types.TaskConnection, error) {
	scope, err := r.authorize(ctx, obj.ID, task.ActionTaskList)
	if err != nil {
		return nil, err
	}

	pageOrderBy := page.OrderBy[coredata.TaskOrderField]{
		Field:     coredata.TaskOrderFieldCreatedAt,
		Direction: page.OrderDirectionDesc,
	}

	if orderBy != nil {
		pageOrderBy = page.OrderBy[coredata.TaskOrderField]{
			Field:     orderBy.Field,
			Direction: orderBy.Direction,
		}
	}

	cursor := types.NewCursor(first, after, last, before, pageOrderBy)

	taskFilter := coredata.NewTaskFilter(nil, nil, nil, nil)
	if filter != nil {
		taskFilter = coredata.NewTaskFilter(
			filter.Query,
			filter.State,
			filter.AssignedToID,
			filter.InternalControlID,
		)
	}

	page, err := r.task.ListForInternalControlID(ctx, scope, obj.ID, cursor, taskFilter)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot list internal control tasks", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return types.NewTaskConnection(page, r, obj.ID, taskFilter), nil
}

// Risks is the resolver for the risks field.
func (r *internalControlResolver) Risks(ctx context.Context, obj *types.InternalControl, first *int, after *page.CursorKey, last *int, before *page.CursorKey, orderBy *types.RiskOrderBy, filter *types.RiskFilter) (*types.RiskConnection, error) {
	scope, err := r.authorize(ctx, obj.ID, probo.ActionRiskList)
	if err != nil {
		return nil, err
	}

	pageOrderBy := page.OrderBy[coredata.RiskOrderField]{
		Field:     coredata.RiskOrderFieldCreatedAt,
		Direction: page.OrderDirectionDesc,
	}

	if orderBy != nil {
		pageOrderBy = page.OrderBy[coredata.RiskOrderField]{
			Field:     orderBy.Field,
			Direction: orderBy.Direction,
		}
	}

	cursor := types.NewCursor(first, after, last, before, pageOrderBy)

	var riskFilter = coredata.NewRiskFilter(nil)
	if filter != nil {
		riskFilter = coredata.NewRiskFilter(filter.Query)
	}

	page, err := r.probo.Risks.ListForInternalControlID(ctx, scope, obj.ID, cursor, riskFilter)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot list internal control risks", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return types.NewRiskConnection(page, r, obj.ID, riskFilter), nil
}

// Controls is the resolver for the controls field.
func (r *internalControlResolver) Controls(ctx context.Context, obj *types.InternalControl, first *int, after *page.CursorKey, last *int, before *page.CursorKey, orderBy *types.ControlOrderBy, filter *types.ControlFilter) (*types.ControlConnection, error) {
	scope, err := r.authorize(ctx, obj.ID, probo.ActionControlList)
	if err != nil {
		return nil, err
	}

	pageOrderBy := page.OrderBy[coredata.ControlOrderField]{
		Field:     coredata.ControlOrderFieldCreatedAt,
		Direction: page.OrderDirectionDesc,
	}

	if orderBy != nil {
		pageOrderBy = page.OrderBy[coredata.ControlOrderField]{
			Field:     orderBy.Field,
			Direction: orderBy.Direction,
		}
	}

	cursor := types.NewCursor(first, after, last, before, pageOrderBy)

	var controlFilter = coredata.NewControlFilter(nil)
	if filter != nil {
		controlFilter = coredata.NewControlFilter(filter.Query)
	}

	page, err := r.probo.Controls.ListForInternalControlID(ctx, scope, obj.ID, cursor, controlFilter)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot list internal control controls", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return types.NewControlConnection(page, r, obj.ID, controlFilter), nil
}

// Documents is the resolver for the documents field.
func (r *internalControlResolver) Documents(ctx context.Context, obj *types.InternalControl, first *int, after *page.CursorKey, last *int, before *page.CursorKey, orderBy *types.DocumentOrderBy, filter *types.DocumentFilter) (*types.DocumentConnection, error) {
	scope, err := r.authorize(ctx, obj.ID, probo.ActionDocumentList)
	if err != nil {
		return nil, err
	}

	pageOrderBy := page.OrderBy[coredata.DocumentOrderField]{
		Field:     coredata.DocumentOrderFieldCreatedAt,
		Direction: page.OrderDirectionDesc,
	}

	if orderBy != nil {
		pageOrderBy = page.OrderBy[coredata.DocumentOrderField]{
			Field:     orderBy.Field,
			Direction: orderBy.Direction,
		}
	}

	cursor := types.NewCursor(first, after, last, before, pageOrderBy)

	var documentFilter = coredata.NewDocumentFilter(nil)
	if filter != nil {
		documentFilter = coredata.NewDocumentFilter(filter.Query).
			WithWriteModes(filter.WriteModes).
			WithDocumentTypes(filter.DocumentTypes).
			WithClassifications(filter.Classifications)
	}

	pg, err := r.probo.Documents.ListForInternalControlID(ctx, scope, obj.ID, cursor, documentFilter)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot list documents", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return types.NewDocumentConnection(pg, r, obj.ID, documentFilter), nil
}

// ThirdParties is the resolver for the thirdParties field.
func (r *internalControlResolver) ThirdParties(ctx context.Context, obj *types.InternalControl, first *int, after *page.CursorKey, last *int, before *page.CursorKey, orderBy *types.ThirdPartyOrderBy) (*types.ThirdPartyConnection, error) {
	scope, err := r.authorize(ctx, obj.ID, probo.ActionThirdPartyList)
	if err != nil {
		return nil, err
	}

	pageOrderBy := page.OrderBy[coredata.ThirdPartyOrderField]{
		Field:     coredata.ThirdPartyOrderFieldCreatedAt,
		Direction: page.OrderDirectionDesc,
	}
	if orderBy != nil {
		pageOrderBy = page.OrderBy[coredata.ThirdPartyOrderField]{
			Field:     orderBy.Field,
			Direction: orderBy.Direction,
		}
	}

	cursor := types.NewCursor(first, after, last, before, pageOrderBy)

	page, err := r.probo.ThirdParties.ListForInternalControlID(ctx, scope, obj.ID, cursor)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot list internal control third parties", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return types.NewThirdPartyConnection(page, r, obj.ID, nil), nil
}

// TreatmentPlans is the resolver for the treatmentPlans field.
func (r *internalControlResolver) TreatmentPlans(ctx context.Context, obj *types.InternalControl, first *int, after *page.CursorKey, last *int, before *page.CursorKey, orderBy *types.TreatmentPlanOrderBy, filter *types.TreatmentPlanFilter, asOf *time.Time) (*types.TreatmentPlanConnection, error) {
	if asOf == nil {
		asOf = obj.AsOf
	}

	scope, err := r.authorize(ctx, obj.ID, riskmanagement.ActionTreatmentPlanList)
	if err != nil {
		return nil, err
	}

	pageOrderBy := page.OrderBy[coredata.TreatmentPlanOrderField]{
		Field:     coredata.TreatmentPlanOrderFieldCreatedAt,
		Direction: page.OrderDirectionDesc,
	}

	if orderBy != nil {
		pageOrderBy = page.OrderBy[coredata.TreatmentPlanOrderField]{
			Field:     orderBy.Field,
			Direction: orderBy.Direction,
		}
	}

	cursor := types.NewCursor(first, after, last, before, pageOrderBy)

	planFilter := coredata.NewTreatmentPlanFilter(nil, nil, nil)
	if filter != nil {
		planFilter = coredata.NewTreatmentPlanFilter(filter.ScoreType, filter.Likelihood, filter.Impact)
	}

	if asOf != nil {
		asOfPage, err := r.riskManagement.ListTreatmentPlansForInternalControlIDAsOf(
			ctx,
			scope,
			obj.ID,
			*asOf,
			cursor,
			planFilter,
		)
		if err != nil {
			if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
				return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
			}

			r.logger.ErrorCtx(ctx, "cannot list internal control treatment plans as of", log.Error(err))

			return nil, gqlutils.Internal(ctx)
		}

		return types.NewTreatmentPlanConnectionAsOf(
			asOfPage.Page,
			r,
			obj.ID,
			planFilter,
			*asOf,
			asOfPage.TotalCount,
			asOfPage.ProgressByID,
		), nil
	}

	page, err := r.riskManagement.ListTreatmentPlansForInternalControlID(ctx, scope, obj.ID, cursor, planFilter)
	if err != nil {
		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		r.logger.ErrorCtx(ctx, "cannot list internal control treatment plans", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return types.NewTreatmentPlanConnection(page, r, obj.ID, planFilter), nil
}

// Permission is the resolver for the permission field.
func (r *internalControlResolver) Permission(ctx context.Context, obj *types.InternalControl, action string) (bool, error) {
	if obj.AsOf != nil {
		return false, nil
	}

	return r.Resolver.Permission(ctx, obj, action)
}

// TotalCount is the resolver for the totalCount field.
func (r *internalControlConnectionResolver) TotalCount(ctx context.Context, obj *types.InternalControlConnection) (int, error) {
	if obj.AsOf != nil {
		return obj.TotalCount, nil
	}

	scope, err := r.authorize(ctx, obj.ParentID, probo.ActionInternalControlList)
	if err != nil {
		return 0, err
	}

	switch obj.Resolver.(type) {
	case *organizationResolver:
		count, err := r.probo.InternalControls.CountForOrganizationID(ctx, scope, obj.ParentID, obj.Filters)
		if err != nil {
			r.logger.ErrorCtx(ctx, "cannot count internal controls", log.Error(err))
			return 0, gqlutils.Internal(ctx)
		}

		return count, nil
	case *controlResolver:
		count, err := r.probo.InternalControls.CountForControlID(ctx, scope, obj.ParentID, obj.Filters)
		if err != nil {
			r.logger.ErrorCtx(ctx, "cannot count internal controls", log.Error(err))
			return 0, gqlutils.Internal(ctx)
		}

		return count, nil
	case *riskResolver:
		count, err := r.probo.InternalControls.CountForRiskID(ctx, scope, obj.ParentID, obj.Filters)
		if err != nil {
			r.logger.ErrorCtx(ctx, "cannot count internal controls", log.Error(err))
			return 0, gqlutils.Internal(ctx)
		}

		return count, nil
	case *thirdPartyResolver:
		count, err := r.probo.InternalControls.CountForThirdPartyID(ctx, scope, obj.ParentID, obj.Filters)
		if err != nil {
			r.logger.ErrorCtx(ctx, "cannot count internal controls", log.Error(err))
			return 0, gqlutils.Internal(ctx)
		}

		return count, nil
	case *treatmentPlanResolver:
		count, err := r.probo.InternalControls.CountForTreatmentPlanID(ctx, scope, obj.ParentID, obj.Filters)
		if err != nil {
			r.logger.ErrorCtx(ctx, "cannot count internal controls", log.Error(err))
			return 0, gqlutils.Internal(ctx)
		}

		return count, nil
	case *taskResolver:
		count, err := r.probo.InternalControls.CountForTaskID(ctx, scope, obj.ParentID, obj.Filters)
		if err != nil {
			r.logger.ErrorCtx(ctx, "cannot count internal controls", log.Error(err))
			return 0, gqlutils.Internal(ctx)
		}

		return count, nil
	}

	r.logger.ErrorCtx(ctx, "unsupported resolver")

	return 0, gqlutils.Internal(ctx)
}

// // CreateInternalControl is the resolver for the createInternalControl field.
func (r *mutationResolver) CreateInternalControl(ctx context.Context, input types.CreateInternalControlInput) (*types.CreateInternalControlPayload, error) {
	scope, err := r.authorize(ctx, input.OrganizationID, probo.ActionInternalControlCreate)
	if err != nil {
		return nil, err
	}

	internalControl, err := r.probo.InternalControls.Create(
		ctx, scope,
		probo.CreateInternalControlRequest{
			OrganizationID:       input.OrganizationID,
			Name:                 input.Name,
			Description:          input.Description,
			Category:             input.Category,
			Code:                 input.Code,
			ControlType:          input.ControlType,
			Nature:               input.Nature,
			OperatingFrequency:   input.OperatingFrequency,
			EvidenceCadence:      input.EvidenceCadence,
			TestingCadence:       input.TestingCadence,
			ImplementationStatus: input.ImplementationStatus,
			OwnerID:              input.OwnerID,
			ReviewerID:           input.ReviewerID,
		},
	)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceAlreadyExists) {
			return nil, gqlutils.Conflict(ctx, err)
		}

		if errors.Is(err, coredata.ErrResourceNotFound) {
			return nil, gqlutils.NotFoundf(ctx, "resource not found")
		}

		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		r.logger.ErrorCtx(ctx, "cannot create internal control", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.CreateInternalControlPayload{
		InternalControlEdge: types.NewInternalControlEdge(internalControl, coredata.InternalControlOrderFieldCreatedAt),
	}, nil
}

// UpdateInternalControl is the resolver for the updateInternalControl field.
func (r *mutationResolver) UpdateInternalControl(ctx context.Context, input types.UpdateInternalControlInput) (*types.UpdateInternalControlPayload, error) {
	scope, err := r.authorize(ctx, input.ID, probo.ActionInternalControlUpdate)
	if err != nil {
		return nil, err
	}

	internalControl, err := r.probo.InternalControls.Update(
		ctx, scope,
		probo.UpdateInternalControlRequest{
			ID:                   input.ID,
			Name:                 input.Name,
			Description:          gqlutils.UnwrapOmittable(input.Description),
			Category:             input.Category,
			State:                input.State,
			Code:                 gqlutils.UnwrapOmittable(input.Code),
			ControlType:          gqlutils.UnwrapOmittable(input.ControlType),
			Nature:               gqlutils.UnwrapOmittable(input.Nature),
			OperatingFrequency:   gqlutils.UnwrapOmittable(input.OperatingFrequency),
			EvidenceCadence:      gqlutils.UnwrapOmittable(input.EvidenceCadence),
			TestingCadence:       gqlutils.UnwrapOmittable(input.TestingCadence),
			ImplementationStatus: input.ImplementationStatus,
			OwnerID:              gqlutils.UnwrapOmittable(input.OwnerID),
			ReviewerID:           gqlutils.UnwrapOmittable(input.ReviewerID),
		},
	)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceAlreadyExists) {
			return nil, gqlutils.Conflict(ctx, err)
		}

		if errors.Is(err, coredata.ErrResourceNotFound) {
			return nil, gqlutils.NotFoundf(ctx, "resource not found")
		}

		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		r.logger.ErrorCtx(ctx, "cannot update internal control", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.UpdateInternalControlPayload{
		InternalControl: types.NewInternalControl(internalControl),
	}, nil
}

// ImportInternalControl is the resolver for the importInternalControl field.
func (r *mutationResolver) ImportInternalControl(ctx context.Context, input types.ImportInternalControlInput) (*types.ImportInternalControlPayload, error) {
	scope, err := r.authorize(ctx, input.OrganizationID, probo.ActionInternalControlImport)
	if err != nil {
		return nil, err
	}

	identity := authn.IdentityFromContext(ctx)

	var req probo.ImportInternalControlRequest
	if err := json.NewDecoder(input.File.File).Decode(&req.InternalControls); err != nil {
		r.logger.ErrorCtx(ctx, "cannot unmarshal internal control", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	req.IdentityID = &identity.ID

	internalControls, err := r.probo.InternalControls.Import(ctx, scope, input.OrganizationID, req)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot import internal control", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	internalControlEdges := make([]*types.InternalControlEdge, len(internalControls.Data))
	for i, internalControl := range internalControls.Data {
		internalControlEdges[i] = types.NewInternalControlEdge(internalControl, coredata.InternalControlOrderFieldCreatedAt)
	}

	return &types.ImportInternalControlPayload{
		InternalControlEdges: internalControlEdges,
	}, nil
}

// DeleteInternalControl is the resolver for the deleteInternalControl field.
func (r *mutationResolver) DeleteInternalControl(ctx context.Context, input types.DeleteInternalControlInput) (*types.DeleteInternalControlPayload, error) {
	scope, err := r.authorize(ctx, input.InternalControlID, probo.ActionInternalControlDelete)
	if err != nil {
		return nil, err
	}

	if err := r.probo.InternalControls.Delete(ctx, scope, input.InternalControlID); err != nil {
		r.logger.ErrorCtx(ctx, "cannot delete internal control", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.DeleteInternalControlPayload{
		DeletedInternalControlID: input.InternalControlID,
	}, nil
}

// CreateInternalControlDocumentMapping is the resolver for the createInternalControlDocumentMapping field.
func (r *mutationResolver) CreateInternalControlDocumentMapping(ctx context.Context, input types.CreateInternalControlDocumentMappingInput) (*types.CreateInternalControlDocumentMappingPayload, error) {
	scope, err := r.authorize(ctx, input.InternalControlID, probo.ActionInternalControlDocumentMappingCreate)
	if err != nil {
		return nil, err
	}

	internalControl, document, err := r.probo.InternalControls.CreateDocumentMapping(ctx, scope, input.InternalControlID, input.DocumentID)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceAlreadyExists) {
			return nil, gqlutils.Conflict(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot create internal control document mapping", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.CreateInternalControlDocumentMappingPayload{
		InternalControlEdge: types.NewInternalControlEdge(internalControl, coredata.InternalControlOrderFieldCreatedAt),
		DocumentEdge:        types.NewDocumentEdge(document, coredata.DocumentOrderFieldTitle),
	}, nil
}

// DeleteInternalControlDocumentMapping is the resolver for the deleteInternalControlDocumentMapping field.
func (r *mutationResolver) DeleteInternalControlDocumentMapping(ctx context.Context, input types.DeleteInternalControlDocumentMappingInput) (*types.DeleteInternalControlDocumentMappingPayload, error) {
	scope, err := r.authorize(ctx, input.InternalControlID, probo.ActionInternalControlDocumentMappingDelete)
	if err != nil {
		return nil, err
	}

	internalControl, document, err := r.probo.InternalControls.DeleteDocumentMapping(ctx, scope, input.InternalControlID, input.DocumentID)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot delete internal control document mapping", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return &types.DeleteInternalControlDocumentMappingPayload{
		DeletedInternalControlID: internalControl.ID,
		DeletedDocumentID:        document.ID,
	}, nil
}

// CreateInternalControlThirdPartyMapping is the resolver for the createInternalControlThirdPartyMapping field.
func (r *mutationResolver) CreateInternalControlThirdPartyMapping(ctx context.Context, input types.CreateInternalControlThirdPartyMappingInput) (*types.CreateInternalControlThirdPartyMappingPayload, error) {
	scope, err := r.authorize(ctx, input.InternalControlID, probo.ActionInternalControlThirdPartyMappingCreate)
	if err != nil {
		return nil, err
	}

	internalControl, thirdParty, err := r.probo.InternalControls.CreateThirdPartyMapping(ctx, scope, input.InternalControlID, input.ThirdPartyID)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot create internal control third party mapping", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return &types.CreateInternalControlThirdPartyMappingPayload{
		InternalControlEdge: types.NewInternalControlEdge(internalControl, coredata.InternalControlOrderFieldCreatedAt),
		ThirdPartyEdge:      types.NewThirdPartyEdge(thirdParty, coredata.ThirdPartyOrderFieldCreatedAt),
	}, nil
}

// DeleteInternalControlThirdPartyMapping is the resolver for the deleteInternalControlThirdPartyMapping field.
func (r *mutationResolver) DeleteInternalControlThirdPartyMapping(ctx context.Context, input types.DeleteInternalControlThirdPartyMappingInput) (*types.DeleteInternalControlThirdPartyMappingPayload, error) {
	scope, err := r.authorize(ctx, input.InternalControlID, probo.ActionInternalControlThirdPartyMappingDelete)
	if err != nil {
		return nil, err
	}

	internalControl, thirdParty, err := r.probo.InternalControls.DeleteThirdPartyMapping(ctx, scope, input.InternalControlID, input.ThirdPartyID)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot delete internal control third party mapping", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return &types.DeleteInternalControlThirdPartyMappingPayload{
		DeletedInternalControlID: internalControl.ID,
		DeletedThirdPartyID:      thirdParty.ID,
	}, nil
}

// InternalControl returns schema.InternalControlResolver implementation.
func (r *Resolver) InternalControl() schema.InternalControlResolver {
	return &internalControlResolver{r}
}

// InternalControlConnection returns schema.InternalControlConnectionResolver implementation.
func (r *Resolver) InternalControlConnection() schema.InternalControlConnectionResolver {
	return &internalControlConnectionResolver{r}
}

type (
	internalControlResolver           struct{ *Resolver }
	internalControlConnectionResolver struct{ *Resolver }
)
