package console_v1

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"

	"github.com/vikstrous/dataloadgen"
	"go.gearno.de/kit/log"
	"go.probo.inc/probo/pkg/coredata"
	"go.probo.inc/probo/pkg/iam"
	"go.probo.inc/probo/pkg/page"
	"go.probo.inc/probo/pkg/probo"
	"go.probo.inc/probo/pkg/riskmanagement"
	"go.probo.inc/probo/pkg/server/api/console/v1/dataloader"
	"go.probo.inc/probo/pkg/server/api/console/v1/schema"
	"go.probo.inc/probo/pkg/server/api/console/v1/types"
	"go.probo.inc/probo/pkg/server/gqlutils"
	"go.probo.inc/probo/pkg/validator"
)

// CreateTreatmentPlan is the resolver for the createTreatmentPlan field.
func (r *mutationResolver) CreateTreatmentPlan(ctx context.Context, input types.CreateTreatmentPlanInput) (*types.CreateTreatmentPlanPayload, error) {
	scope, err := r.authorize(ctx, input.RiskAnalysisID, riskmanagement.ActionTreatmentPlanCreate)
	if err != nil {
		return nil, err
	}

	tp, err := r.riskManagement.CreateTreatmentPlan(
		ctx,
		scope,
		riskmanagement.CreateTreatmentPlanRequest{
			RiskID:             input.RiskID,
			RiskAnalysisID:     input.RiskAnalysisID,
			Treatment:          input.Treatment,
			OwnerID:            input.OwnerID,
			InherentLikelihood: input.InherentLikelihood,
			InherentImpact:     input.InherentImpact,
			ResidualLikelihood: input.ResidualLikelihood,
			ResidualImpact:     input.ResidualImpact,
		},
	)
	if err != nil {
		switch {
		case errors.Is(err, coredata.ErrResourceAlreadyExists):
			return nil, gqlutils.Conflictf(ctx, "treatment plan already exists for this risk and analysis")
		case errors.Is(err, coredata.ErrResourceNotFound):
			return nil, gqlutils.NotFound(ctx, err)
		default:
			if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
				return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
			}

			r.logger.ErrorCtx(ctx, "cannot create treatment plan", log.Error(err))

			return nil, gqlutils.Internal(ctx)
		}
	}

	return &types.CreateTreatmentPlanPayload{
		TreatmentPlanEdge: types.NewTreatmentPlanEdge(tp, coredata.TreatmentPlanOrderFieldCreatedAt),
	}, nil
}

// UpdateTreatmentPlan is the resolver for the updateTreatmentPlan field.
func (r *mutationResolver) UpdateTreatmentPlan(ctx context.Context, input types.UpdateTreatmentPlanInput) (*types.UpdateTreatmentPlanPayload, error) {
	scope, err := r.authorize(ctx, input.ID, riskmanagement.ActionTreatmentPlanUpdate)
	if err != nil {
		return nil, err
	}

	tp, err := r.riskManagement.UpdateTreatmentPlan(
		ctx,
		scope,
		riskmanagement.UpdateTreatmentPlanRequest{
			ID:                 input.ID,
			Treatment:          input.Treatment,
			OwnerID:            gqlutils.UnwrapOmittable(input.OwnerID),
			InherentLikelihood: input.InherentLikelihood,
			InherentImpact:     input.InherentImpact,
			ResidualLikelihood: input.ResidualLikelihood,
			ResidualImpact:     input.ResidualImpact,
		},
	)
	if err != nil {
		switch {
		case errors.Is(err, coredata.ErrResourceNotFound):
			return nil, gqlutils.NotFound(ctx, err)
		default:
			if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
				return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
			}

			r.logger.ErrorCtx(ctx, "cannot update treatment plan", log.Error(err))

			return nil, gqlutils.Internal(ctx)
		}
	}

	return &types.UpdateTreatmentPlanPayload{TreatmentPlan: types.NewTreatmentPlan(tp)}, nil
}

// DeleteTreatmentPlan is the resolver for the deleteTreatmentPlan field.
func (r *mutationResolver) DeleteTreatmentPlan(ctx context.Context, input types.DeleteTreatmentPlanInput) (*types.DeleteTreatmentPlanPayload, error) {
	scope, err := r.authorize(ctx, input.TreatmentPlanID, riskmanagement.ActionTreatmentPlanDelete)
	if err != nil {
		return nil, err
	}

	if err := r.riskManagement.DeleteTreatmentPlan(ctx, scope, input.TreatmentPlanID); err != nil {
		switch {
		case errors.Is(err, coredata.ErrResourceNotFound):
			return nil, gqlutils.NotFound(ctx, err)
		default:
			r.logger.ErrorCtx(ctx, "cannot delete treatment plan", log.Error(err))

			return nil, gqlutils.Internal(ctx)
		}
	}

	return &types.DeleteTreatmentPlanPayload{DeletedTreatmentPlanID: input.TreatmentPlanID}, nil
}

// CreateTreatmentPlanMeasureMapping is the resolver for the createTreatmentPlanMeasureMapping field.
func (r *mutationResolver) CreateTreatmentPlanMeasureMapping(ctx context.Context, input types.CreateTreatmentPlanMeasureMappingInput) (*types.CreateTreatmentPlanMeasureMappingPayload, error) {
	scope, err := r.authorize(ctx, input.TreatmentPlanID, riskmanagement.ActionTreatmentPlanUpdate)
	if err != nil {
		return nil, err
	}

	tp, measure, err := r.riskManagement.CreateMeasureMapping(ctx, scope, input.TreatmentPlanID, input.MeasureID)
	if err != nil {
		switch {
		case errors.Is(err, coredata.ErrResourceAlreadyExists):
			return nil, gqlutils.Conflictf(ctx, "measure already linked to this treatment plan")
		case errors.Is(err, coredata.ErrResourceNotFound):
			return nil, gqlutils.NotFound(ctx, err)
		default:
			if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
				return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
			}

			r.logger.ErrorCtx(ctx, "cannot create treatment plan measure mapping", log.Error(err))

			return nil, gqlutils.Internal(ctx)
		}
	}

	return &types.CreateTreatmentPlanMeasureMappingPayload{
		TreatmentPlanEdge: types.NewTreatmentPlanEdge(tp, coredata.TreatmentPlanOrderFieldCreatedAt),
		MeasureEdge:       types.NewMeasureEdge(measure, coredata.MeasureOrderFieldCreatedAt),
	}, nil
}

// DeleteTreatmentPlanMeasureMapping is the resolver for the deleteTreatmentPlanMeasureMapping field.
func (r *mutationResolver) DeleteTreatmentPlanMeasureMapping(ctx context.Context, input types.DeleteTreatmentPlanMeasureMappingInput) (*types.DeleteTreatmentPlanMeasureMappingPayload, error) {
	scope, err := r.authorize(ctx, input.TreatmentPlanID, riskmanagement.ActionTreatmentPlanUpdate)
	if err != nil {
		return nil, err
	}

	tp, measure, err := r.riskManagement.DeleteMeasureMapping(ctx, scope, input.TreatmentPlanID, input.MeasureID)
	if err != nil {
		switch {
		case errors.Is(err, coredata.ErrResourceNotFound):
			return nil, gqlutils.NotFound(ctx, err)
		default:
			r.logger.ErrorCtx(ctx, "cannot delete treatment plan measure mapping", log.Error(err))
			return nil, gqlutils.Internal(ctx)
		}
	}

	return &types.DeleteTreatmentPlanMeasureMappingPayload{
		DeletedTreatmentPlanID: tp.ID,
		DeletedMeasureID:       measure.ID,
		TreatmentPlan:          types.NewTreatmentPlan(tp),
	}, nil
}

// NetLikelihood is the resolver for the netLikelihood field.
func (r *treatmentPlanResolver) NetLikelihood(ctx context.Context, obj *types.TreatmentPlan) (int, error) {
	likelihood, _, _, err := r.treatmentPlanNetScores(ctx, obj)
	return likelihood, err
}

// NetImpact is the resolver for the netImpact field.
func (r *treatmentPlanResolver) NetImpact(ctx context.Context, obj *types.TreatmentPlan) (int, error) {
	_, impact, _, err := r.treatmentPlanNetScores(ctx, obj)
	return impact, err
}

// NetRiskScore is the resolver for the netRiskScore field.
func (r *treatmentPlanResolver) NetRiskScore(ctx context.Context, obj *types.TreatmentPlan) (int, error) {
	_, _, score, err := r.treatmentPlanNetScores(ctx, obj)
	return score, err
}

// Owner is the resolver for the owner field.
func (r *treatmentPlanResolver) Owner(ctx context.Context, obj *types.TreatmentPlan) (*types.Profile, error) {
	if _, err := r.authorize(ctx, obj.Owner.ID, iam.ActionMembershipProfileGet); err != nil {
		return nil, err
	}

	loaders := dataloader.FromContext(ctx)

	owner, err := loaders.Profile.Load(ctx, obj.Owner.ID)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) || errors.Is(err, dataloadgen.ErrNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot get owner", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return types.NewProfile(owner), nil
}

// Risk is the resolver for the risk field.
func (r *treatmentPlanResolver) Risk(ctx context.Context, obj *types.TreatmentPlan) (*types.Risk, error) {
	scope, err := r.authorize(ctx, obj.Risk.ID, probo.ActionRiskGet)
	if err != nil {
		return nil, err
	}

	risk, err := r.probo.Risks.Get(ctx, scope, obj.Risk.ID)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot get risk", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return types.NewRisk(risk), nil
}

// RiskAnalysis is the resolver for the riskAnalysis field.
func (r *treatmentPlanResolver) RiskAnalysis(ctx context.Context, obj *types.TreatmentPlan) (*types.RiskAnalysis, error) {
	scope, err := r.authorize(ctx, obj.RiskAnalysis.ID, riskmanagement.ActionRiskAnalysisGet)
	if err != nil {
		return nil, err
	}

	analysis, err := r.riskManagement.Get(ctx, scope, obj.RiskAnalysis.ID)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot get risk analysis", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return types.NewRiskAnalysis(analysis), nil
}

// Organization is the resolver for the organization field.
func (r *treatmentPlanResolver) Organization(ctx context.Context, obj *types.TreatmentPlan) (*types.Organization, error) {
	if _, err := r.authorize(ctx, obj.ID, probo.ActionOrganizationGet); err != nil {
		return nil, err
	}

	loaders := dataloader.FromContext(ctx)

	organization, err := loaders.Organization.Load(ctx, obj.Organization.ID)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) || errors.Is(err, dataloadgen.ErrNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot get organization", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return types.NewOrganization(organization), nil
}

// Measures is the resolver for the measures field.
func (r *treatmentPlanResolver) Measures(ctx context.Context, obj *types.TreatmentPlan, first *int, after *page.CursorKey, last *int, before *page.CursorKey, orderBy *types.MeasureOrderBy, filter *types.MeasureFilter) (*types.MeasureConnection, error) {
	scope, err := r.authorize(ctx, obj.ID, probo.ActionMeasureList)
	if err != nil {
		return nil, err
	}

	pageOrderBy := page.OrderBy[coredata.MeasureOrderField]{
		Field:     coredata.MeasureOrderFieldCreatedAt,
		Direction: page.OrderDirectionDesc,
	}

	if orderBy != nil {
		pageOrderBy = page.OrderBy[coredata.MeasureOrderField]{
			Field:     orderBy.Field,
			Direction: orderBy.Direction,
		}
	}

	cursor := types.NewCursor(first, after, last, before, pageOrderBy)

	var measureFilter = coredata.NewMeasureFilter(nil, nil, nil)
	if filter != nil {
		measureFilter = coredata.NewMeasureFilter(filter.Query, filter.State, filter.Category)
	}

	page, err := r.probo.Measures.ListForTreatmentPlanID(ctx, scope, obj.ID, cursor, measureFilter)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot list treatment plan measures", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return types.NewMeasureConnection(page, r, obj.ID, measureFilter), nil
}

// Permission is the resolver for the permission field.
func (r *treatmentPlanResolver) Permission(ctx context.Context, obj *types.TreatmentPlan, action string) (bool, error) {
	return r.Resolver.Permission(ctx, obj, action)
}

// TotalCount is the resolver for the totalCount field.
func (r *treatmentPlanConnectionResolver) TotalCount(ctx context.Context, obj *types.TreatmentPlanConnection) (int, error) {
	scope, err := r.authorize(ctx, obj.ParentID, riskmanagement.ActionTreatmentPlanList)
	if err != nil {
		return 0, err
	}

	switch obj.Resolver.(type) {
	case *organizationResolver:
		count, err := r.riskManagement.CountTreatmentPlansForOrganizationID(ctx, scope, obj.ParentID)
		if err != nil {
			r.logger.ErrorCtx(ctx, "cannot count treatment plans", log.Error(err))
			return 0, gqlutils.Internal(ctx)
		}

		return count, nil
	case *riskResolver:
		count, err := r.riskManagement.CountTreatmentPlansForRiskID(ctx, scope, obj.ParentID)
		if err != nil {
			r.logger.ErrorCtx(ctx, "cannot count treatment plans", log.Error(err))
			return 0, gqlutils.Internal(ctx)
		}

		return count, nil
	case *riskAnalysisResolver:
		count, err := r.riskManagement.CountTreatmentPlansForRiskAnalysisID(ctx, scope, obj.ParentID)
		if err != nil {
			r.logger.ErrorCtx(ctx, "cannot count treatment plans", log.Error(err))
			return 0, gqlutils.Internal(ctx)
		}

		return count, nil
	case *measureResolver:
		count, err := r.riskManagement.CountTreatmentPlansForMeasureID(ctx, scope, obj.ParentID)
		if err != nil {
			r.logger.ErrorCtx(ctx, "cannot count treatment plans", log.Error(err))
			return 0, gqlutils.Internal(ctx)
		}

		return count, nil
	}

	r.logger.ErrorCtx(ctx, "unsupported resolver")

	return 0, gqlutils.Internal(ctx)
}

// TreatmentPlan returns schema.TreatmentPlanResolver implementation.
func (r *Resolver) TreatmentPlan() schema.TreatmentPlanResolver { return &treatmentPlanResolver{r} }

// TreatmentPlanConnection returns schema.TreatmentPlanConnectionResolver implementation.
func (r *Resolver) TreatmentPlanConnection() schema.TreatmentPlanConnectionResolver {
	return &treatmentPlanConnectionResolver{r}
}

type (
	treatmentPlanResolver           struct{ *Resolver }
	treatmentPlanConnectionResolver struct{ *Resolver }
)
