import { IconListStack } from "@probo/ui";

import type { DocumentTemplate } from "./types";

export const incidentResponseTemplate: DocumentTemplate = {
  id: "incident-response-plan",
  icon: IconListStack,
  name: "Incident Response",
  documentType: "PLAN",
  classification: "CONFIDENTIAL",
  title: "Incident Response Plan",
  content: [
    "<h1>🚨 Incident Response Plan</h1>",
    "<p></p>",

    "<table><thead><tr><th>Property</th><th>Details</th></tr></thead><tbody>",
    "<tr><td>📋 <strong>Document Owner</strong></td><td>Security Operations Team</td></tr>",
    "<tr><td>🏷️ <strong>Classification</strong></td><td>Confidential</td></tr>",
    "<tr><td>📅 <strong>Effective Date</strong></td><td><em>[Enter date]</em></td></tr>",
    "<tr><td>🔄 <strong>Next Review</strong></td><td><em>[Enter date + 6 months]</em></td></tr>",
    "<tr><td>📌 <strong>Version</strong></td><td>1.0</td></tr>",
    "<tr><td>✅ <strong>Approved By</strong></td><td><em>[Name, Title]</em></td></tr>",
    "</tbody></table>",
    "<p></p>",
    "<hr>",
    "<p></p>",

    // 1 · Purpose & Objectives
    "<h2>1 · Purpose &amp; Objectives</h2>",
    "<p>This plan defines how <strong>[Organization Name]</strong> will detect, respond to, and recover from security incidents. Our objectives are to:</p>",
    "<ol>",
    "<li><strong>Minimize business impact</strong> and operational downtime</li>",
    "<li><strong>Preserve evidence</strong> for investigation and legal proceedings</li>",
    "<li><strong>Ensure regulatory compliance</strong> with notification requirements</li>",
    "<li><strong>Improve defenses</strong> through lessons learned</li>",
    "</ol>",
    "<p></p>",
    "<blockquote><p>⚡ <strong>Quick Reference:</strong> If you suspect a security incident right now, skip to <strong>Section 3</strong> for immediate response steps and <strong>Section 5</strong> for the contact list.</p></blockquote>",
    "<p></p>",

    // 2 · Severity Classification
    "<h2>2 · Severity Classification</h2>",
    "<p></p>",
    "<table><thead><tr><th>Level</th><th>Name</th><th>Description</th><th>SLA</th><th>Examples</th></tr></thead><tbody>",
    "<tr><td>🔴</td><td><strong>P1 — Critical</strong></td><td>Active breach, widespread impact</td><td>≤ 15 min</td><td>Ransomware · Data exfiltration · Root compromise</td></tr>",
    "<tr><td>🟠</td><td><strong>P2 — High</strong></td><td>Confirmed threat, limited scope</td><td>≤ 1 hour</td><td>Malware on endpoint · Stolen credentials in use</td></tr>",
    "<tr><td>🟡</td><td><strong>P3 — Medium</strong></td><td>Suspicious activity, needs investigation</td><td>≤ 4 hours</td><td>Phishing click · Anomalous traffic · Policy violation</td></tr>",
    "<tr><td>🔵</td><td><strong>P4 — Low</strong></td><td>Minor event, no immediate risk</td><td>≤ 24 hours</td><td>Failed logins · Spam · False positive alert</td></tr>",
    "</tbody></table>",
    "<p></p>",

    // 3 · Response Phases
    "<h2>3 · Response Phases</h2>",
    "<p></p>",

    "<h3>Phase 1 — 🔍 Detection &amp; Triage</h3>",
    "<p>The first responder must complete these steps immediately:</p>",
    "<ul data-type=\"taskList\">",
    "<li data-type=\"taskItem\" data-checked=\"false\">Verify the alert — confirm it is a real incident, not a false positive</li>",
    "<li data-type=\"taskItem\" data-checked=\"false\">Assign severity level using the matrix above</li>",
    "<li data-type=\"taskItem\" data-checked=\"false\">Create an incident ticket with initial details (who, what, when, where)</li>",
    "<li data-type=\"taskItem\" data-checked=\"false\">Assign an <strong>Incident Commander</strong> (IC) to lead the response</li>",
    "<li data-type=\"taskItem\" data-checked=\"false\">Notify stakeholders per the escalation matrix in Section 4</li>",
    "</ul>",
    "<p></p>",

    "<h3>Phase 2 — 🛑 Containment</h3>",
    "<p></p>",
    "<table><thead><tr><th>Action Type</th><th>Steps</th><th>Goal</th></tr></thead><tbody>",
    "<tr><td><strong>Short-term</strong></td><td>Isolate affected systems · Block malicious IPs · Disable compromised accounts</td><td>Stop the bleeding</td></tr>",
    "<tr><td><strong>Long-term</strong></td><td>Apply emergency patches · Rotate credentials · Increase monitoring</td><td>Prevent reinfection</td></tr>",
    "<tr><td><strong>Evidence</strong></td><td>Capture memory dumps · Clone affected disks · Export logs with timestamps</td><td>Preserve chain of custody</td></tr>",
    "</tbody></table>",
    "<p></p>",

    "<h3>Phase 3 — 🧹 Eradication</h3>",
    "<ul>",
    "<li>Identify and eliminate the <strong>root cause</strong> (vulnerability, misconfig, malware, compromised account)</li>",
    "<li>Apply <strong>permanent patches</strong> and security hardening</li>",
    "<li>Scan all related systems for <strong>indicators of compromise</strong> (IOCs)</li>",
    "<li>Verify threat actor no longer has <strong>any access</strong> to the environment</li>",
    "</ul>",
    "<p></p>",

    "<h3>Phase 4 — ♻️ Recovery</h3>",
    "<ul>",
    "<li>Restore systems from <strong>verified clean backups</strong></li>",
    "<li>Reintroduce systems to production <strong>gradually</strong> with enhanced monitoring</li>",
    "<li>Verify data integrity and <strong>confirm normal operation</strong></li>",
    "<li>Monitor for <strong>72 hours post-recovery</strong> for signs of recurrence</li>",
    "</ul>",
    "<p></p>",

    "<h3>Phase 5 — 📝 Post-Incident Review</h3>",
    "<p>Conduct a <strong>blameless post-mortem</strong> within 5 business days. Document:</p>",
    "<ul>",
    "<li><strong>Timeline</strong> — What happened, when, and in what order</li>",
    "<li><strong>Root Cause</strong> — Technical and process failures that allowed the incident</li>",
    "<li><strong>What Worked</strong> — Effective detection and response actions</li>",
    "<li><strong>What Didn't</strong> — Gaps, delays, and miscommunications</li>",
    "<li><strong>Action Items</strong> — Specific improvements with owners and deadlines</li>",
    "</ul>",
    "<p></p>",

    // 4 · Escalation Matrix
    "<h2>4 · Escalation Matrix</h2>",
    "<p></p>",
    "<table><thead><tr><th>Severity</th><th>Notify Immediately</th><th>Notify Within 1 Hour</th><th>Communication Channel</th></tr></thead><tbody>",
    "<tr><td>🔴 P1</td><td>CISO · CEO · Legal Counsel</td><td>Board · PR · Affected customers</td><td>📞 Phone call + War Room</td></tr>",
    "<tr><td>🟠 P2</td><td>CISO · IT Director</td><td>Department Heads</td><td>💬 Slack #incidents + Email</td></tr>",
    "<tr><td>🟡 P3</td><td>Security Team Lead</td><td>CISO (summary)</td><td>🎫 Incident ticket + Slack</td></tr>",
    "<tr><td>🔵 P4</td><td>On-call analyst</td><td>Security Team Lead (summary)</td><td>🎫 Incident ticket only</td></tr>",
    "</tbody></table>",
    "<p></p>",

    // 5 · Emergency Contacts
    "<h2>5 · Emergency Contacts</h2>",
    "<p></p>",
    "<table><thead><tr><th>Role</th><th>Name</th><th>Phone</th><th>Email</th></tr></thead><tbody>",
    "<tr><td>🎯 Incident Commander</td><td><em>[Name]</em></td><td><em>[Phone]</em></td><td><em>[Email]</em></td></tr>",
    "<tr><td>🛡️ CISO</td><td><em>[Name]</em></td><td><em>[Phone]</em></td><td><em>[Email]</em></td></tr>",
    "<tr><td>⚖️ Legal Counsel</td><td><em>[Name]</em></td><td><em>[Phone]</em></td><td><em>[Email]</em></td></tr>",
    "<tr><td>📢 Communications / PR</td><td><em>[Name]</em></td><td><em>[Phone]</em></td><td><em>[Email]</em></td></tr>",
    "<tr><td>🔬 External Forensics</td><td><em>[Vendor Name]</em></td><td><em>[Phone]</em></td><td><em>[Email]</em></td></tr>",
    "<tr><td>🚔 Law Enforcement</td><td><em>[Agency]</em></td><td><em>[Phone]</em></td><td>—</td></tr>",
    "</tbody></table>",
    "<p></p>",

    // 6 · Testing & Maintenance
    "<h2>6 · Testing &amp; Maintenance</h2>",
    "<ul data-type=\"taskList\">",
    "<li data-type=\"taskItem\" data-checked=\"false\">Conduct tabletop exercises — <strong>minimum twice per year</strong></li>",
    "<li data-type=\"taskItem\" data-checked=\"false\">Run a simulated incident drill — <strong>annually</strong></li>",
    "<li data-type=\"taskItem\" data-checked=\"false\">Review and update this plan — <strong>every 6 months</strong></li>",
    "<li data-type=\"taskItem\" data-checked=\"false\">Verify all emergency contacts are current — <strong>quarterly</strong></li>",
    "<li data-type=\"taskItem\" data-checked=\"false\">Update runbooks for new systems and threat scenarios</li>",
    "</ul>",
    "<p></p>",
    "<hr>",
    "<p></p>",
    "<blockquote><p>📎 <strong>Related Documents:</strong> Information Security Policy · Business Continuity Plan · Disaster Recovery Procedure · Communication Plan · Forensics Handbook</p></blockquote>",
    "<p></p>",
    "<p><em>All incident response team members must review this plan and confirm familiarity with their roles before an incident occurs.</em></p>",
  ].join(""),
};
