package trust_v1

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"errors"

	"go.gearno.de/kit/log"
	"go.probo.inc/probo/pkg/coredata"
	"go.probo.inc/probo/pkg/mailman"
	"go.probo.inc/probo/pkg/page"
	"go.probo.inc/probo/pkg/server/api/authn"
	"go.probo.inc/probo/pkg/server/api/compliancepage"
	"go.probo.inc/probo/pkg/server/api/trust/v1/types"
	"go.probo.inc/probo/pkg/server/gqlutils"
	"go.probo.inc/probo/pkg/validator"
)

// SubscribeToMailingList is the resolver for the subscribeToMailingList field.
func (r *mutationResolver) SubscribeToMailingList(ctx context.Context) (*types.SubscribeToMailingListPayload, error) {
	trustCenter := compliancepage.CompliancePageFromContext(ctx)
	if trustCenter.MailingListID == nil {
		return nil, gqlutils.NotFoundf(ctx, "mailing list not found")
	}

	identity := authn.IdentityFromContext(ctx)

	subscriber, err := r.mailman.CreateSubscriber(
		ctx,
		&mailman.CreateSubscriberRequest{
			MailingListID: *trustCenter.MailingListID,
			Email:         identity.EmailAddress,
			FullName:      identity.FullName,
		},
	)
	if err != nil {
		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}
		if errors.Is(err, mailman.ErrSubscriberAlreadyExist) {
			return nil, gqlutils.Conflictf(ctx, "already subscribed to this mailing list")
		}
		r.logger.ErrorCtx(ctx, "cannot subscribe to mailing list", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return &types.SubscribeToMailingListPayload{
		Subscription: types.NewMailingListSubscriber(subscriber),
	}, nil
}

// UnsubscribeFromMailingList is the resolver for the unsubscribeFromMailingList field.
func (r *mutationResolver) UnsubscribeFromMailingList(ctx context.Context) (*types.UnsubscribeFromMailingListPayload, error) {
	trustCenter := compliancepage.CompliancePageFromContext(ctx)
	if trustCenter.MailingListID == nil {
		return nil, gqlutils.NotFoundf(ctx, "mailing list not found")
	}

	identity := authn.IdentityFromContext(ctx)

	subscriber, err := r.mailman.GetSubscriber(ctx, *trustCenter.MailingListID, identity.EmailAddress)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot get mailing list subscription", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}
	if subscriber == nil {
		return nil, gqlutils.NotFoundf(ctx, "not subscribed to this mailing list")
	}

	if err := r.mailman.DeleteSubscriber(ctx, subscriber.ID); err != nil {
		if errors.Is(err, mailman.ErrSubscriberNotFound) {
			return nil, gqlutils.NotFoundf(ctx, "not subscribed to this mailing list")
		}
		r.logger.ErrorCtx(ctx, "cannot unsubscribe from mailing list", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return &types.UnsubscribeFromMailingListPayload{DeletedMailingListSubscriberID: &subscriber.ID}, nil
}

// ViewerSubscription is the resolver for the viewerSubscription field.
func (r *trustCenterResolver) ViewerSubscription(ctx context.Context, obj *types.TrustCenter) (*types.MailingListSubscriber, error) {
	trustCenter := compliancepage.CompliancePageFromContext(ctx)
	if trustCenter.MailingListID == nil {
		return nil, nil
	}

	identity := authn.IdentityFromContext(ctx)
	if identity == nil {
		return nil, nil
	}

	subscriber, err := r.mailman.GetSubscriber(ctx, *trustCenter.MailingListID, identity.EmailAddress)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot get mailing list subscription", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	if subscriber == nil {
		return nil, nil
	}

	return types.NewMailingListSubscriber(subscriber), nil
}

// Updates is the resolver for the updates field.
func (r *trustCenterResolver) Updates(ctx context.Context, obj *types.TrustCenter, first *int, after *page.CursorKey, last *int, before *page.CursorKey) (*types.MailingListUpdateConnection, error) {
	trustService := r.TrustService(ctx, obj.ID.TenantID())

	tc, err := trustService.TrustCenters.Get(ctx, obj.ID)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot load trust center", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	if tc.MailingListID == nil {
		return &types.MailingListUpdateConnection{Edges: []*types.MailingListUpdateEdge{}, PageInfo: &types.PageInfo{}}, nil
	}

	pageOrderBy := page.OrderBy[coredata.MailingListUpdateOrderField]{
		Field:     coredata.MailingListUpdateOrderFieldUpdatedAt,
		Direction: page.OrderDirectionDesc,
	}
	cursor := types.NewCursor(first, after, last, before, pageOrderBy)

	result, err := r.mailman.ListSentMailingListUpdates(ctx, *tc.MailingListID, cursor)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot list mailing list updates", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return types.NewMailingListUpdateConnection(result), nil
}
