package trust_v1

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"go.gearno.de/kit/log"
	"go.probo.inc/probo/pkg/coredata"
	"go.probo.inc/probo/pkg/page"
	"go.probo.inc/probo/pkg/server/api/authn"
	"go.probo.inc/probo/pkg/server/api/compliancepage"
	"go.probo.inc/probo/pkg/server/api/trust/v1/types"
	"go.probo.inc/probo/pkg/server/gqlutils"
	"go.probo.inc/probo/pkg/trust"
)

// CreateRightsRequest is the resolver for the createRightsRequest field.
func (r *mutationResolver) CreateRightsRequest(ctx context.Context, input types.CreateRightsRequestInput) (*types.CreateRightsRequestPayload, error) {
	identity := authn.IdentityFromContext(ctx)
	if identity == nil {
		return nil, gqlutils.Unauthenticatedf(ctx, "authentication is required to submit a request")
	}

	compliancePage := compliancepage.CompliancePageFromContext(ctx)
	scope := coredata.NewScopeFromObjectID(compliancePage.OrganizationID)

	rightsRequest, err := r.trust.RightsRequests.Create(
		ctx,
		scope,
		&trust.CreateRightsRequest{
			OrganizationID: compliancePage.OrganizationID,
			RequestType:    input.RequestType,
			DataSubject:    input.DataSubject,
			Contact:        identity.EmailAddress.String(),
			Details:        input.Details,
		},
	)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot create rights request", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return &types.CreateRightsRequestPayload{
		RightsRequestEdge: types.NewRightsRequestEdge(
			rightsRequest,
			coredata.RightsRequestOrderFieldCreatedAt,
		),
	}, nil
}

// MyRightsRequests is the resolver for the myRightsRequests field.
func (r *queryResolver) MyRightsRequests(ctx context.Context, first *int, after *page.CursorKey, last *int, before *page.CursorKey) (*types.RightsRequestConnection, error) {
	pageOrderBy := page.OrderBy[coredata.RightsRequestOrderField]{
		Field:     coredata.RightsRequestOrderFieldCreatedAt,
		Direction: page.OrderDirectionDesc,
	}
	cursor := types.NewCursor(first, after, last, before, pageOrderBy)

	identity := authn.IdentityFromContext(ctx)
	if identity == nil {
		emptyPage := page.NewPage([]*coredata.RightsRequest{}, cursor)
		return types.NewRightsRequestConnection(emptyPage), nil
	}

	compliancePage := compliancepage.CompliancePageFromContext(ctx)
	scope := coredata.NewScopeFromObjectID(compliancePage.OrganizationID)

	result, err := r.trust.RightsRequests.ListForOrganizationIDAndContact(
		ctx,
		scope,
		compliancePage.OrganizationID,
		identity.EmailAddress.String(),
		cursor,
	)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot list rights requests", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return types.NewRightsRequestConnection(result), nil
}
