// Copyright (c) 2026 Probo Inc <hello@probo.com>.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package automerge_test

import (
	"context"
	"os"
	"path/filepath"
	"sort"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"go.probo.inc/probo/pkg/automerge"
)

// TestOfficialBenchmarkBatteryFixtures runs the documents generated by the real
// upstream benchmark-battery constructors through Rust -> Go -> Rust and
// Rust -> Go -> Rust -> Go. It is opt-in because the official typing fixture has
// ten thousand changes and is intended for the weekly battery job.
func TestOfficialBenchmarkBatteryFixtures(t *testing.T) {
	t.Parallel()

	directory := os.Getenv("AUTOMERGE_OFFICIAL_BATTERY_FIXTURES")
	if directory == "" {
		t.Skip("AUTOMERGE_OFFICIAL_BATTERY_FIXTURES is not configured")
	}

	fixtures, err := filepath.Glob(filepath.Join(directory, "*.automerge"))
	require.NoError(t, err)
	require.NotEmpty(t, fixtures)
	sort.Strings(fixtures)

	for index, fixture := range fixtures {
		t.Run(filepath.Base(fixture), func(t *testing.T) {
			t.Parallel()

			ctx := context.Background()

			data, err := os.ReadFile(fixture)
			require.NoError(t, err)

			nativeDocument, err := automerge.Load(ctx, data, actor(byte(0x80+index)))
			require.NoError(t, err)
			closeDocument(t, nativeDocument)

			referenceDocument, err := automerge.LoadReference(
				ctx,
				data,
				actor(byte(0x90+index)),
			)
			require.NoError(t, err)
			closeDocument(t, referenceDocument)

			assert.Equal(
				t,
				sortedHeadHex(t, ctx, referenceDocument),
				sortedHeadHex(t, ctx, nativeDocument),
			)

			// Rust fixture -> Go save -> Rust load.
			nativeSaved, err := nativeDocument.Save(ctx)
			require.NoError(t, err)

			referenceReloaded, err := automerge.LoadReference(
				ctx,
				nativeSaved,
				actor(byte(0xa0+index)),
			)
			require.NoError(t, err)
			closeDocument(t, referenceReloaded)

			assert.Equal(
				t,
				sortedHeadHex(t, ctx, referenceDocument),
				sortedHeadHex(t, ctx, referenceReloaded),
			)

			// Rust fixture -> Rust save -> Go load.
			referenceSaved, err := referenceDocument.Save(ctx)
			require.NoError(t, err)

			nativeReloaded, err := automerge.Load(
				ctx,
				referenceSaved,
				actor(byte(0xb0+index)),
			)
			require.NoError(t, err)
			closeDocument(t, nativeReloaded)

			assert.Equal(
				t,
				sortedHeadHex(t, ctx, nativeDocument),
				sortedHeadHex(t, ctx, nativeReloaded),
			)
		})
	}
}
