// Copyright (c) 2026 Probo Inc <hello@probo.com>.
//
// Permission to use, copy, modify, and/or distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
// REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
// AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
// INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
// LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
// OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.

package shared

// ValidEvents is the set of event types accepted by the webhook
// create and update commands. Keep in sync with
// pkg/coredata/webhook_event_type.go.
var ValidEvents = []string{
	"THIRD_PARTY_CREATED",
	"THIRD_PARTY_UPDATED",
	"THIRD_PARTY_DELETED",
	"USER_CREATED",
	"USER_UPDATED",
	"USER_DELETED",
	"OBLIGATION_CREATED",
	"OBLIGATION_UPDATED",
	"OBLIGATION_DELETED",
	"DOCUMENT_CREATED",
	"DOCUMENT_UPDATED",
	"DOCUMENT_ARCHIVED",
	"DOCUMENT_UNARCHIVED",
	"DOCUMENT_DELETED",
	"DOCUMENT_VERSION_CREATED",
	"DOCUMENT_VERSION_UPDATED",
	"DOCUMENT_VERSION_PUBLISHED",
	"DOCUMENT_VERSION_REJECTED",
	"DOCUMENT_VERSION_DELETED",
	"DOCUMENT_VERSION_SIGNATURE_REQUESTED",
	"DOCUMENT_VERSION_SIGNATURE_SIGNED",
	"DOCUMENT_VERSION_SIGNATURE_CANCELLED",
	"DOCUMENT_VERSION_APPROVAL_QUORUM_REQUESTED",
	"DOCUMENT_VERSION_APPROVAL_QUORUM_UPDATED",
	"DOCUMENT_VERSION_APPROVAL_QUORUM_APPROVED",
	"DOCUMENT_VERSION_APPROVAL_QUORUM_REJECTED",
	"DOCUMENT_VERSION_APPROVAL_QUORUM_VOIDED",
}
