// Code generated by mcpgen. DO NOT EDIT.

package server

import (
	"context"
	"github.com/modelcontextprotocol/go-sdk/mcp"
	"go.probo.inc/probo/pkg/server/api/mcp/v1/types"
)

// ResolverInterface defines the interface that must be implemented by the parent resolver
type ResolverInterface interface {
	ListOrganizationsTool(ctx context.Context, req *mcp.CallToolRequest, input *types.ListOrganizationsInput) (*mcp.CallToolResult, types.ListOrganizationsOutput, error)
	ListVendorsTool(ctx context.Context, req *mcp.CallToolRequest, input *types.ListVendorsInput) (*mcp.CallToolResult, types.ListVendorsOutput, error)
	ListPeopleTool(ctx context.Context, req *mcp.CallToolRequest, input *types.ListPeopleInput) (*mcp.CallToolResult, types.ListPeopleOutput, error)
	AddVendorTool(ctx context.Context, req *mcp.CallToolRequest, input *types.AddVendorInput) (*mcp.CallToolResult, types.AddVendorOutput, error)
	UpdateVendorTool(ctx context.Context, req *mcp.CallToolRequest, input *types.UpdateVendorInput) (*mcp.CallToolResult, types.UpdateVendorOutput, error)
	GetPeopleTool(ctx context.Context, req *mcp.CallToolRequest, input *types.GetPeopleInput) (*mcp.CallToolResult, types.GetPeopleOutput, error)
	AddPeopleTool(ctx context.Context, req *mcp.CallToolRequest, input *types.AddPeopleInput) (*mcp.CallToolResult, types.AddPeopleOutput, error)
	ListRisksTool(ctx context.Context, req *mcp.CallToolRequest, input *types.ListRisksInput) (*mcp.CallToolResult, types.ListRisksOutput, error)
	GetRiskTool(ctx context.Context, req *mcp.CallToolRequest, input *types.GetRiskInput) (*mcp.CallToolResult, types.GetRiskOutput, error)
	AddRiskTool(ctx context.Context, req *mcp.CallToolRequest, input *types.AddRiskInput) (*mcp.CallToolResult, types.AddRiskOutput, error)
	UpdateRiskTool(ctx context.Context, req *mcp.CallToolRequest, input *types.UpdateRiskInput) (*mcp.CallToolResult, types.UpdateRiskOutput, error)
	ListMeasuresTool(ctx context.Context, req *mcp.CallToolRequest, input *types.ListMeasuresInput) (*mcp.CallToolResult, types.ListMeasuresOutput, error)
	GetMeasureTool(ctx context.Context, req *mcp.CallToolRequest, input *types.GetMeasureInput) (*mcp.CallToolResult, types.GetMeasureOutput, error)
	AddMeasureTool(ctx context.Context, req *mcp.CallToolRequest, input *types.AddMeasureInput) (*mcp.CallToolResult, types.AddMeasureOutput, error)
	UpdateMeasureTool(ctx context.Context, req *mcp.CallToolRequest, input *types.UpdateMeasureInput) (*mcp.CallToolResult, types.UpdateMeasureOutput, error)
	ListFrameworksTool(ctx context.Context, req *mcp.CallToolRequest, input *types.ListFrameworksInput) (*mcp.CallToolResult, types.ListFrameworksOutput, error)
	GetFrameworkTool(ctx context.Context, req *mcp.CallToolRequest, input *types.GetFrameworkInput) (*mcp.CallToolResult, types.GetFrameworkOutput, error)
	AddFrameworkTool(ctx context.Context, req *mcp.CallToolRequest, input *types.AddFrameworkInput) (*mcp.CallToolResult, types.AddFrameworkOutput, error)
	UpdateFrameworkTool(ctx context.Context, req *mcp.CallToolRequest, input *types.UpdateFrameworkInput) (*mcp.CallToolResult, types.UpdateFrameworkOutput, error)
}

// New creates a new MCP server instance with all handlers registered.
// Returns a fully configured *mcp.Server ready to be used with any transport.
func New(resolver ResolverInterface) *mcp.Server {
	server := mcp.NewServer(
		&mcp.Implementation{
			Name:    "Probo MCP Server",
			Version: "1.0.0",
		},
		nil,
	)

	registerToolHandlers(server, resolver)

	return server
}

func registerToolHandlers(server *mcp.Server, resolver ResolverInterface) {
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "listOrganizations",
			Description:  "List all organizations the user has access to",
			InputSchema:  types.ListOrganizationsToolInputSchema,
			OutputSchema: types.ListOrganizationsToolOutputSchema,
		},
		resolver.ListOrganizationsTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "listVendors",
			Description:  "List all vendors for the organization",
			InputSchema:  types.ListVendorsToolInputSchema,
			OutputSchema: types.ListVendorsToolOutputSchema,
		},
		resolver.ListVendorsTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "listPeople",
			Description:  "List all people for the organization",
			InputSchema:  types.ListPeopleToolInputSchema,
			OutputSchema: types.ListPeopleToolOutputSchema,
		},
		resolver.ListPeopleTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "addVendor",
			Description:  "Add a new vendor to the organization",
			InputSchema:  types.AddVendorToolInputSchema,
			OutputSchema: types.AddVendorToolOutputSchema,
		},
		resolver.AddVendorTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "updateVendor",
			Description:  "Update an existing vendor",
			InputSchema:  types.UpdateVendorToolInputSchema,
			OutputSchema: types.UpdateVendorToolOutputSchema,
		},
		resolver.UpdateVendorTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "getPeople",
			Description:  "Get a people by ID",
			InputSchema:  types.GetPeopleToolInputSchema,
			OutputSchema: types.GetPeopleToolOutputSchema,
		},
		resolver.GetPeopleTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "addPeople",
			Description:  "Add a new people to the organization",
			InputSchema:  types.AddPeopleToolInputSchema,
			OutputSchema: types.AddPeopleToolOutputSchema,
		},
		resolver.AddPeopleTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "listRisks",
			Description:  "List all risks for the organization",
			InputSchema:  types.ListRisksToolInputSchema,
			OutputSchema: types.ListRisksToolOutputSchema,
		},
		resolver.ListRisksTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "getRisk",
			Description:  "Get a risk by ID",
			InputSchema:  types.GetRiskToolInputSchema,
			OutputSchema: types.GetRiskToolOutputSchema,
		},
		resolver.GetRiskTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "addRisk",
			Description:  "Add a new risk to the organization",
			InputSchema:  types.AddRiskToolInputSchema,
			OutputSchema: types.AddRiskToolOutputSchema,
		},
		resolver.AddRiskTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "updateRisk",
			Description:  "Update an existing risk",
			InputSchema:  types.UpdateRiskToolInputSchema,
			OutputSchema: types.UpdateRiskToolOutputSchema,
		},
		resolver.UpdateRiskTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "listMeasures",
			Description:  "List all measures for the organization",
			InputSchema:  types.ListMeasuresToolInputSchema,
			OutputSchema: types.ListMeasuresToolOutputSchema,
		},
		resolver.ListMeasuresTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "getMeasure",
			Description:  "Get a measure by ID",
			InputSchema:  types.GetMeasureToolInputSchema,
			OutputSchema: types.GetMeasureToolOutputSchema,
		},
		resolver.GetMeasureTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "addMeasure",
			Description:  "Add a new measure to the organization",
			InputSchema:  types.AddMeasureToolInputSchema,
			OutputSchema: types.AddMeasureToolOutputSchema,
		},
		resolver.AddMeasureTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "updateMeasure",
			Description:  "Update an existing measure",
			InputSchema:  types.UpdateMeasureToolInputSchema,
			OutputSchema: types.UpdateMeasureToolOutputSchema,
		},
		resolver.UpdateMeasureTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "listFrameworks",
			Description:  "List all frameworks for the organization",
			InputSchema:  types.ListFrameworksToolInputSchema,
			OutputSchema: types.ListFrameworksToolOutputSchema,
		},
		resolver.ListFrameworksTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "getFramework",
			Description:  "Get a framework by ID",
			InputSchema:  types.GetFrameworkToolInputSchema,
			OutputSchema: types.GetFrameworkToolOutputSchema,
		},
		resolver.GetFrameworkTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "addFramework",
			Description:  "Add a new framework to the organization",
			InputSchema:  types.AddFrameworkToolInputSchema,
			OutputSchema: types.AddFrameworkToolOutputSchema,
		},
		resolver.AddFrameworkTool,
	)
	mcp.AddTool(
		server,
		&mcp.Tool{
			Name:         "updateFramework",
			Description:  "Update an existing framework",
			InputSchema:  types.UpdateFrameworkToolInputSchema,
			OutputSchema: types.UpdateFrameworkToolOutputSchema,
		},
		resolver.UpdateFrameworkTool,
	)
}
