// Copyright (c) 2025 Probo Inc <hello@getprobo.com>.
//
// Permission to use, copy, modify, and/or distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
// REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
// AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
// INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
// LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
// OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.

package probo

import (
	"go.probo.inc/probo/pkg/coredata"
	"go.probo.inc/probo/pkg/iam"
)

// legacyActionMapping maps entity types to a mapping of legacy actions to new namespaced actions.
// This is used during the migration period to translate old action strings to new policy actions.
var legacyActionMapping = map[uint16]map[iam.Action]iam.Action{
	coredata.OrganizationEntityType: {
		iam.ActionGet:                              ActionOrganizationGet,
		iam.ActionGetLogoUrl:                       ActionOrganizationGetLogoUrl,
		iam.ActionGetHorizontalLogoUrl:             ActionOrganizationGetHorizontalLogoUrl,
		iam.ActionListDocuments:                    ActionDocumentList,
		iam.ActionListSignableDocuments:            ActionDocumentList,
		iam.ActionPeoples:                          ActionPeopleList,
		iam.ActionTotalCount:                       ActionOrganizationGet,
		iam.ActionListFrameworks:                   ActionFrameworkList,
		iam.ActionListControls:                     ActionControlList,
		iam.ActionListVendors:                      ActionVendorList,
		iam.ActionListPeople:                       ActionPeopleList,
		iam.ActionListMeasures:                     ActionMeasureList,
		iam.ActionListRisks:                        ActionRiskList,
		iam.ActionListAssets:                       ActionAssetList,
		iam.ActionListData:                         ActionDatumList,
		iam.ActionListAudits:                       ActionAuditList,
		iam.ActionListNonconformities:              ActionNonconformityList,
		iam.ActionListObligations:                  ActionObligationList,
		iam.ActionListContinualImprovements:        ActionContinualImprovementList,
		iam.ActionListProcessingActivities:         ActionProcessingActivityList,
		iam.ActionListSnapshots:                    ActionSnapshotList,
		iam.ActionAcceptInvitation:                 iam.ActionIAMInvitationAccept,
		iam.ActionListTrustCenterFiles:             ActionTrustCenterFileList,
		iam.ActionGetTrustCenter:                   ActionTrustCenterGet,
		iam.ActionMemberships:                      iam.ActionIAMOrganizationListMembers,
		iam.ActionListMembers:                      iam.ActionIAMOrganizationListMembers,
		iam.ActionListInvitations:                  iam.ActionIAMOrganizationListInvitations,
		iam.ActionListSlackConnections:             ActionSlackConnectionList,
		iam.ActionGetCustomDomain:                  ActionCustomDomainGet,
		iam.ActionListMeetings:                     ActionMeetingList,
		iam.ActionListTasks:                        ActionTaskList,
		iam.ActionUpdateOrganization:               ActionOrganizationGet,
		iam.ActionDeleteOrganizationHorizontalLogo: ActionOrganizationGet,
		iam.ActionCreateTrustCenter:                ActionTrustCenterGet,
		iam.ActionInviteUser:                       iam.ActionIAMOrganizationInviteMember,
		iam.ActionUpdateMembership:                 iam.ActionIAMMembershipUpdate,
		iam.ActionCreatePeople:                     ActionPeopleCreate,
		iam.ActionCreateVendor:                     ActionVendorCreate,
		iam.ActionCreateFramework:                  ActionFrameworkCreate,
		iam.ActionImportFramework:                  ActionFrameworkImport,
		iam.ActionCreateControl:                    ActionControlCreate,
		iam.ActionCreateMeasure:                    ActionMeasureCreate,
		iam.ActionImportMeasure:                    ActionMeasureImport,
		iam.ActionCreateMeeting:                    ActionMeetingCreate,
		iam.ActionCreateTask:                       ActionTaskCreate,
		iam.ActionCreateRisk:                       ActionRiskCreate,
		iam.ActionCreateDocument:                   ActionDocumentCreate,
		iam.ActionCreateAsset:                      ActionAssetCreate,
		iam.ActionCreateDatum:                      ActionDatumCreate,
		iam.ActionCreateAudit:                      ActionAuditCreate,
		iam.ActionCreateNonconformity:              ActionNonconformityCreate,
		iam.ActionCreateObligation:                 ActionObligationCreate,
		iam.ActionCreateContinualImprovement:       ActionContinualImprovementCreate,
		iam.ActionCreateProcessingActivity:         ActionProcessingActivityCreate,
		iam.ActionCreateSnapshot:                   ActionSnapshotCreate,
		iam.ActionCreateTrustCenterFile:            ActionTrustCenterFileCreate,
		iam.ActionSendSigningNotifications:         ActionDocumentSendSigningNotifications,
		iam.ActionRemoveMember:                     iam.ActionIAMOrganizationRemoveMember,
		iam.ActionCreateCustomDomain:               ActionCustomDomainCreate,
		iam.ActionDeleteCustomDomain:               ActionCustomDomainDelete,
	},
	coredata.TrustCenterEntityType: {
		iam.ActionGet:                        ActionTrustCenterGet,
		iam.ActionGetOrganization:            ActionOrganizationGet,
		iam.ActionUpdateTrustCenter:          ActionTrustCenterUpdate,
		iam.ActionUploadTrustCenterNDA:       ActionTrustCenterNonDisclosureAgreementUpload,
		iam.ActionDeleteTrustCenterNDA:       ActionTrustCenterNonDisclosureAgreementDelete,
		iam.ActionCreateTrustCenterAccess:    ActionTrustCenterAccessCreate,
		iam.ActionCreateTrustCenterReference: ActionTrustCenterReferenceCreate,
	},
	coredata.TrustCenterAccessEntityType: {
		iam.ActionUpdateTrustCenterAccess: ActionTrustCenterAccessUpdate,
		iam.ActionDeleteTrustCenterAccess: ActionTrustCenterAccessDelete,
	},
	coredata.TrustCenterReferenceEntityType: {
		iam.ActionUpdateTrustCenterReference: ActionTrustCenterReferenceUpdate,
		iam.ActionDeleteTrustCenterReference: ActionTrustCenterReferenceDelete,
	},
	coredata.TrustCenterFileEntityType: {
		iam.ActionUpdateTrustCenterFile: ActionTrustCenterFileUpdate,
		iam.ActionDeleteTrustCenterFile: ActionTrustCenterFileDelete,
	},
	coredata.IdentityEntityType: {
		iam.ActionGet: iam.ActionIAMIdentityGet,
	},
	coredata.MembershipEntityType: {
		iam.ActionGet:           iam.ActionIAMMembershipGet,
		iam.ActionGetAuthMethod: iam.ActionIAMMembershipGet,
	},
	coredata.InvitationEntityType: {
		iam.ActionGet:              iam.ActionIAMInvitationGet,
		iam.ActionGetOrganization:  iam.ActionIAMInvitationGet,
		iam.ActionDeleteInvitation: iam.ActionIAMInvitationDelete,
	},
	coredata.PeopleEntityType: {
		iam.ActionGet:          ActionPeopleGet,
		iam.ActionUpdatePeople: ActionPeopleUpdate,
		iam.ActionDeletePeople: ActionPeopleDelete,
	},
	coredata.VendorEntityType: {
		iam.ActionGet:                                    ActionVendorList,
		iam.ActionGetOrganization:                        ActionOrganizationGet,
		iam.ActionGetBusinessOwner:                       ActionPeopleGet,
		iam.ActionGetSecurityOwner:                       ActionPeopleGet,
		iam.ActionUpdateVendor:                           ActionVendorUpdate,
		iam.ActionDeleteVendor:                           ActionVendorDelete,
		iam.ActionCreateVendorContact:                    ActionVendorContactCreate,
		iam.ActionCreateVendorService:                    ActionVendorServiceCreate,
		iam.ActionUploadVendorComplianceReport:           ActionVendorComplianceReportUpload,
		iam.ActionUploadVendorBusinessAssociateAgreement: ActionVendorBusinessAssociateAgreementUpload,
		iam.ActionDeleteVendorBusinessAssociateAgreement: ActionVendorBusinessAssociateAgreementDelete,
		iam.ActionUploadVendorDataPrivacyAgreement:       ActionVendorDataPrivacyAgreementUpload,
		iam.ActionCreateVendorRiskAssessment:             ActionVendorRiskAssessmentCreate,
		iam.ActionAssessVendor:                           ActionVendorAssess,
	},
	coredata.VendorComplianceReportEntityType: {
		iam.ActionGet:                          ActionVendorList,
		iam.ActionGetVendor:                    ActionVendorList,
		iam.ActionDeleteVendorComplianceReport: ActionVendorComplianceReportDelete,
	},
	coredata.VendorBusinessAssociateAgreementEntityType: {
		iam.ActionGet:        ActionVendorList,
		iam.ActionGetVendor:  ActionVendorList,
		iam.ActionGetFileUrl: ActionFileDownloadUrl,
		iam.ActionUpdateVendorBusinessAssociateAgreement: ActionVendorBusinessAssociateAgreementUpdate,
		iam.ActionDeleteVendorBusinessAssociateAgreement: ActionVendorBusinessAssociateAgreementDelete,
	},
	coredata.VendorContactEntityType: {
		iam.ActionGet:                 ActionVendorList,
		iam.ActionGetVendor:           ActionVendorList,
		iam.ActionUpdateVendorContact: ActionVendorContactUpdate,
		iam.ActionDeleteVendorContact: ActionVendorContactDelete,
	},
	coredata.VendorServiceEntityType: {
		iam.ActionGet:                 ActionVendorList,
		iam.ActionGetVendor:           ActionVendorList,
		iam.ActionUpdateVendorService: ActionVendorServiceUpdate,
		iam.ActionDeleteVendorService: ActionVendorServiceDelete,
	},
	coredata.VendorDataPrivacyAgreementEntityType: {
		iam.ActionGet:                              ActionVendorList,
		iam.ActionGetVendor:                        ActionVendorList,
		iam.ActionGetFileUrl:                       ActionFileDownloadUrl,
		iam.ActionUpdateVendorDataPrivacyAgreement: ActionVendorDataPrivacyAgreementUpdate,
		iam.ActionDeleteVendorDataPrivacyAgreement: ActionVendorDataPrivacyAgreementDelete,
	},
	coredata.VendorRiskAssessmentEntityType: {
		iam.ActionGet: ActionVendorList,
	},
	coredata.FrameworkEntityType: {
		iam.ActionGet:                                   ActionFrameworkGet,
		iam.ActionGetOrganization:                       ActionOrganizationGet,
		iam.ActionListControls:                          ActionControlList,
		iam.ActionCreateControl:                         ActionControlCreate,
		iam.ActionUpdateFramework:                       ActionFrameworkUpdate,
		iam.ActionDeleteFramework:                       ActionFrameworkDelete,
		iam.ActionGenerateFrameworkStateOfApplicability: ActionFrameworkStateOfApplicabilityGenerate,
		iam.ActionExportFramework:                       ActionFrameworkExport,
	},
	coredata.ControlEntityType: {
		iam.ActionGet:                          ActionControlList,
		iam.ActionGetFramework:                 ActionFrameworkGet,
		iam.ActionListMeasures:                 ActionMeasureList,
		iam.ActionListDocuments:                ActionDocumentList,
		iam.ActionListAudits:                   ActionAuditList,
		iam.ActionListSnapshots:                ActionSnapshotList,
		iam.ActionUpdateControl:                ActionControlUpdate,
		iam.ActionDeleteControl:                ActionControlDelete,
		iam.ActionCreateControlMeasureMapping:  ActionControlMeasureMappingCreate,
		iam.ActionCreateControlDocumentMapping: ActionControlDocumentMappingCreate,
		iam.ActionDeleteControlMeasureMapping:  ActionControlMeasureMappingDelete,
		iam.ActionDeleteControlDocumentMapping: ActionControlDocumentMappingDelete,
		iam.ActionCreateControlAuditMapping:    ActionControlAuditMappingCreate,
		iam.ActionDeleteControlAuditMapping:    ActionControlAuditMappingDelete,
		iam.ActionCreateControlSnapshotMapping: ActionControlSnapshotMappingCreate,
		iam.ActionDeleteControlSnapshotMapping: ActionControlSnapshotMappingDelete,
	},
	coredata.MeasureEntityType: {
		iam.ActionGet:                   ActionMeasureGet,
		iam.ActionListTasks:             ActionTaskList,
		iam.ActionListEvidences:         ActionEvidenceList,
		iam.ActionListRisks:             ActionRiskList,
		iam.ActionListControls:          ActionControlList,
		iam.ActionTotalCount:            ActionMeasureList,
		iam.ActionUpdateMeasure:         ActionMeasureUpdate,
		iam.ActionDeleteMeasure:         ActionMeasureDelete,
		iam.ActionUploadMeasureEvidence: ActionMeasureEvidenceUpload,
	},
	coredata.TaskEntityType: {
		iam.ActionGet:             ActionTaskGet,
		iam.ActionGetAssignedTo:   ActionPeopleGet,
		iam.ActionGetOrganization: ActionOrganizationGet,
		iam.ActionGetMeasure:      ActionMeasureGet,
		iam.ActionListEvidences:   ActionEvidenceList,
		iam.ActionUpdateTask:      ActionTaskUpdate,
		iam.ActionDeleteTask:      ActionTaskDelete,
		iam.ActionAssignTask:      ActionTaskAssign,
		iam.ActionUnassignTask:    ActionTaskUnassign,
	},
	coredata.EvidenceEntityType: {
		iam.ActionGet:            ActionEvidenceList,
		iam.ActionGetFile:        ActionFileGet,
		iam.ActionGetTask:        ActionTaskGet,
		iam.ActionGetMeasure:     ActionMeasureList,
		iam.ActionDeleteEvidence: ActionEvidenceDelete,
	},
	coredata.DocumentEntityType: {
		iam.ActionGet:                         ActionDocumentGet,
		iam.ActionGetOwner:                    ActionPeopleGet,
		iam.ActionGetOrganization:             ActionOrganizationGet,
		iam.ActionGetSigned:                   ActionDocumentList,
		iam.ActionGetSignableDocument:         ActionDocumentList,
		iam.ActionListSignableDocumentVersion: ActionDocumentList,
		iam.ActionBulkExportDocuments:         ActionDocumentList,
		iam.ActionTotalCount:                  ActionDocumentList,
		iam.ActionListControls:                ActionControlList,
		iam.ActionListVersions:                ActionDocumentVersionList,
		iam.ActionUpdateDocument:              ActionDocumentUpdate,
		iam.ActionDeleteDocument:              ActionDocumentDelete,
		iam.ActionBulkDeleteDocuments:         ActionDocumentDelete,
		iam.ActionPublishDocumentVersion:      ActionDocumentVersionPublish,
		iam.ActionBulkPublishDocumentVersions: ActionDocumentVersionPublish,
		iam.ActionGenerateDocumentChangelog:   ActionDocumentChangelogGenerate,
		iam.ActionCreateDraftDocumentVersion:  ActionDocumentDraftVersionCreate,
		iam.ActionDeleteDraftDocumentVersion:  ActionDocumentVersionDeleteDraft,
		iam.ActionUpdateDocumentVersion:       ActionDocumentVersionUpdate,
		iam.ActionRequestSignature:            ActionDocumentVersionSignatureRequest,
		iam.ActionBulkRequestSignatures:       ActionDocumentVersionSignatureRequest,
		iam.ActionSendSigningNotifications:    ActionDocumentSendSigningNotifications,
		iam.ActionCancelSignatureRequest:      ActionDocumentVersionCancelSignature,
	},
	coredata.DocumentVersionEntityType: {
		iam.ActionGet:                              ActionDocumentVersionGet,
		iam.ActionGetFile:                          ActionFileGet,
		iam.ActionGetOwner:                         ActionPeopleGet,
		iam.ActionGetDocument:                      ActionDocumentGet,
		iam.ActionGetSigned:                        ActionDocumentVersionGet,
		iam.ActionSignatures:                       ActionDocumentVersionSignatureList,
		iam.ActionExportDocumentVersionPDF:         ActionDocumentVersionExportPDF,
		iam.ActionExportSignableVersionDocumentPDF: ActionDocumentVersionExportSignable,
		iam.ActionSignDocument:                     ActionDocumentVersionSign,
		iam.ActionUpdateDocumentVersion:            ActionDocumentVersionUpdate,
		iam.ActionRequestSignature:                 ActionDocumentVersionSignatureRequest,
		iam.ActionDeleteDraftDocumentVersion:       ActionDocumentVersionDeleteDraft,
	},
	coredata.DocumentVersionSignatureEntityType: {
		iam.ActionGet:             ActionDocumentVersionSignatureList,
		iam.ActionDocumentVersion: ActionDocumentVersionGet,
		iam.ActionSignedBy:        ActionPeopleGet,
	},
	coredata.RiskEntityType: {
		iam.ActionGet:                         ActionRiskList,
		iam.ActionGetOwner:                    ActionPeopleGet,
		iam.ActionGetOrganization:             ActionOrganizationGet,
		iam.ActionTotalCount:                  ActionRiskList,
		iam.ActionListControls:                ActionControlList,
		iam.ActionListMeasures:                ActionMeasureList,
		iam.ActionListDocuments:               ActionDocumentList,
		iam.ActionListObligations:             ActionObligationList,
		iam.ActionUpdateRisk:                  ActionRiskUpdate,
		iam.ActionDeleteRisk:                  ActionRiskDelete,
		iam.ActionCreateRiskMeasureMapping:    ActionRiskMeasureMappingCreate,
		iam.ActionDeleteRiskMeasureMapping:    ActionRiskMeasureMappingDelete,
		iam.ActionCreateRiskDocumentMapping:   ActionRiskDocumentMappingCreate,
		iam.ActionDeleteRiskDocumentMapping:   ActionRiskDocumentMappingDelete,
		iam.ActionCreateRiskObligationMapping: ActionRiskObligationMappingCreate,
		iam.ActionDeleteRiskObligationMapping: ActionRiskObligationMappingDelete,
	},
	coredata.AssetEntityType: {
		iam.ActionGet:             ActionAssetList,
		iam.ActionGetOwner:        ActionPeopleGet,
		iam.ActionListVendors:     ActionVendorList,
		iam.ActionGetAssetType:    ActionAssetList,
		iam.ActionGetOrganization: ActionOrganizationGet,
		iam.ActionUpdateAsset:     ActionAssetUpdate,
		iam.ActionDeleteAsset:     ActionAssetDelete,
	},
	coredata.DatumEntityType: {
		iam.ActionGet:             ActionDatumList,
		iam.ActionGetOwner:        ActionPeopleGet,
		iam.ActionGetOrganization: ActionOrganizationGet,
		iam.ActionListVendors:     ActionVendorList,
		iam.ActionUpdateDatum:     ActionDatumUpdate,
		iam.ActionDeleteDatum:     ActionDatumDelete,
	},
	coredata.AuditEntityType: {
		iam.ActionGet:               ActionAuditGet,
		iam.ActionGetFile:           ActionFileGet,
		iam.ActionGetFramework:      ActionFrameworkGet,
		iam.ActionGetOrganization:   ActionOrganizationGet,
		iam.ActionReport:            ActionAuditList,
		iam.ActionReportUrl:         ActionAuditList,
		iam.ActionListControls:      ActionControlList,
		iam.ActionUpdateAudit:       ActionAuditUpdate,
		iam.ActionDeleteAudit:       ActionAuditDelete,
		iam.ActionUploadAuditReport: ActionAuditReportUpload,
		iam.ActionDeleteAuditReport: ActionAuditReportDelete,
	},
	coredata.ReportEntityType: {
		iam.ActionGet:             ActionReportGet,
		iam.ActionGetAudit:        ActionAuditGet,
		iam.ActionGetFile:         ActionFileGet,
		iam.ActionGetOrganization: ActionOrganizationGet,
		iam.ActionGetSnapshot:     ActionSnapshotList,
		iam.ActionDownloadUrl:     ActionReportDownloadUrlGet,
	},
	coredata.NonconformityEntityType: {
		iam.ActionGet:                 ActionNonconformityList,
		iam.ActionGetOwner:            ActionPeopleGet,
		iam.ActionGetOrganization:     ActionOrganizationGet,
		iam.ActionAudit:               ActionAuditList,
		iam.ActionUpdateNonconformity: ActionNonconformityUpdate,
		iam.ActionDeleteNonconformity: ActionNonconformityDelete,
	},
	coredata.ObligationEntityType: {
		iam.ActionGet:              ActionObligationList,
		iam.ActionGetOrganization:  ActionOrganizationGet,
		iam.ActionGetOwner:         ActionPeopleGet,
		iam.ActionListRisks:        ActionRiskList,
		iam.ActionUpdateObligation: ActionObligationUpdate,
		iam.ActionDeleteObligation: ActionObligationDelete,
	},
	coredata.ContinualImprovementEntityType: {
		iam.ActionGet:                        ActionContinualImprovementList,
		iam.ActionGetOwner:                   ActionPeopleGet,
		iam.ActionGetOrganization:            ActionOrganizationGet,
		iam.ActionUpdateContinualImprovement: ActionContinualImprovementUpdate,
		iam.ActionDeleteContinualImprovement: ActionContinualImprovementDelete,
	},
	coredata.ProcessingActivityEntityType: {
		iam.ActionGet:                      ActionProcessingActivityList,
		iam.ActionGetOrganization:          ActionOrganizationGet,
		iam.ActionListVendors:              ActionVendorList,
		iam.ActionUpdateProcessingActivity: ActionProcessingActivityUpdate,
		iam.ActionDeleteProcessingActivity: ActionProcessingActivityDelete,
	},
	coredata.SnapshotEntityType: {
		iam.ActionGet:             ActionSnapshotList,
		iam.ActionGetOrganization: ActionOrganizationGet,
		iam.ActionListControls:    ActionControlList,
		iam.ActionDeleteSnapshot:  ActionSnapshotDelete,
	},
	coredata.CustomDomainEntityType: {
		iam.ActionGet:                ActionCustomDomainGet,
		iam.ActionDeleteCustomDomain: ActionCustomDomainDelete,
	},
	coredata.FileEntityType: {
		iam.ActionGet:         ActionFileGet,
		iam.ActionDownloadUrl: ActionFileDownloadUrl,
	},
	coredata.MeetingEntityType: {
		iam.ActionGet:             ActionMeetingList,
		iam.ActionGetOrganization: ActionOrganizationGet,
		iam.ActionTotalCount:      ActionMeetingList,
		iam.ActionUpdateMeeting:   ActionMeetingUpdate,
		iam.ActionDeleteMeeting:   ActionMeetingDelete,
	},
}

// MapLegacyAction converts a legacy action string to a new namespaced action.
// Returns the new action and true if found, or empty string and false if not mapped.
func MapLegacyAction(entityType uint16, legacyAction iam.Action) (iam.Action, bool) {
	if entityActions, ok := legacyActionMapping[entityType]; ok {
		if newAction, ok := entityActions[legacyAction]; ok {
			return newAction, true
		}
	}
	return "", false
}
