name: "trufflehog"

on:
  push:
    branches:
      - "main"
  pull_request:

permissions:
  contents: read

jobs:
  scan:
    runs-on: "runs-on=${{ github.run_id }}/runner=2cpu-linux-x64/extras=s3-cache"
    permissions:
      contents: "read"
    steps:
      - uses: "actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0" # v6
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: "runs-on/action@d141ef83eb66d096ce8afc767e09115a65c63b60" # v2
      - uses: "trufflesecurity/trufflehog@f446421baf832d6356c42c1743d99abff52ff334" # main
        with:
          extra_args: "--results=verified,unknown --exclude-paths=.trufflehog-exclude"
