name: "trufflehog"

on:
  push:
    branches:
      - "main"
  pull_request:

permissions:
  contents: read

jobs:
  scan:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v6"
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: "trufflesecurity/trufflehog@e48f9039c82786db50685e8ef7d980b209f06186" # main
        with:
          extra_args: "--results=verified,unknown --exclude-paths=.trufflehog-exclude"
