name: "trufflehog"

on:
  push:
    branches:
      - "main"
  pull_request:

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  scan:
    runs-on: "runs-on=${{ github.run_id }}/runner=2cpu-linux-x64/extras=s3-cache"
    permissions:
      contents: "read"
    steps:
      - uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v6
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: "runs-on/action@efac073ea2507ec18797de3a81704201ade11d9d" # v2
      - uses: "trufflesecurity/trufflehog@4dd8831c5f12599465d4d45c3c447b4018a34c85" # main
        with:
          extra_args: "--results=verified,unknown"
